### ISSUE TITLE
Today 16:00 beer @ Suite

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#101]
It is located at the first floor of the Linnaeusborg, in the back.

@christophnetz 
@EllyJet 
@JamesAndrews91 
@JorikdeBoer 
@Lumphie 
@LykeStuurman 

Beer is on @richelbilderbeek

**Comment by Lumphie** [comment]
:D

**Comment by richelbilderbeek** [comment]
Brilliant map:

![map](https://cloud.githubusercontent.com/assets/2098230/20797046/7e8e3bd4-b7d9-11e6-9fec-fe9e6f480a5c.png)

**Comment by Lumphie** [comment]
https://youtu.be/FwU-GSbrYms

Awesome directions!
