### ISSUE TITLE
Make boost work for kewe

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#103]
Branch|[![Travis CI logo](TravisCI.png)](https://travis-ci.org)
---|---
kewe|[![Build Status](https://travis-ci.org/richelbilderbeek/pbdmms.svg?branch=kewe)](https://travis-ci.org/richelbilderbeek/pbdmms)

**Comment by richelbilderbeek** [comment]
You can do it :+1:

**Comment by Lumphie** [comment]
Travis is running this now.
