### ISSUE TITLE
jaan: Suggestion: ES.1: Prefer the standard library to other libraries and to "handcrafted code"

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#107]
Consider rule `ES.1: Prefer the standard library to other libraries and to "handcrafted code"` from [the C++ Core Guidlines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-lib) and replace this function:

```
void swap(Individual &A, Individual &B)
// swaps Individual A with Individual B.
{
    Individual C = A;
    A = B;
    B = C;
    return;
}
```

by just using `std::swap`.

**Comment by JamesAndrews91** [comment]
Done!
