### ISSUE TITLE
Histogram.csv file not working for historgram png

### ISSUE THREAD

**Issue by LykeStuurman** [richelbilderbeek/pbdmms#109]
@richelbilderbeek 
[Histogram.csv.zip](https://github.com/richelbilderbeek/pbdmms/files/633582/Histogram.csv.zip)

**Comment by richelbilderbeek** [comment]
Program should throw on exception when the file is empty.

**Comment by richelbilderbeek** [comment]
@LykeStuurman : I guess you also want me to fix non-trivial CSVs? If yes, please submit those :+1:
