### ISSUE TITLE
cine: Suggestion: add profiling run

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#112]
On Travis, `./cine` is run and profiled. That run finishes in less than [0.005 seconds](https://travis-ci.org/richelbilderbeek/pbdmms/builds/181965713#L1868).

I suggest to let (me let) Travis call `./cine --profile` that runs your simulation with a certain set of parameters. These parameters are chosen, that Travis will finish the run in at most 10 minutes. Profiling information is vital for runtime speed improvement, and you get it already for -close to- free now.

You can see `ribi_main.cpp` and `lyke_main.cpp` how this is done by me and lyke.

If you have questions, let me know.

**Comment by christophnetz** [comment]
Hey Richel, sounds good! I' a little sick today so I'll join a bit later

**Comment by christophnetz** [comment]
Jup, did it (forgot to close issue)
