### ISSUE TITLE
Hidden report

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#116]
Where is @richelbilderbeek 's concept report about his speciation model including the beautiful picture of the PBD-model: "Should protracted speciation be incorporated in phylogenetic tree construction methods?"

**Comment by richelbilderbeek** [comment]
It is (hidden) [here](https://github.com/richelbilderbeek/distancer_article)

**Comment by JorikdeBoer** [comment]
The beautiful picture is here: https://github.com/richelbilderbeek/wirittte_article/blob/master/pbd_explanation.png !!

**Comment by richelbilderbeek** [comment]
Looks like you've found it!
