### ISSUE TITLE
Fix OCLint complaints

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#120]
The master build is broken because of OCLint.

- [x] @LykeStuurman 
- [x] @JamesAndrews91 
- [ ] @christophnetz 

`
/home/travis/build/richelbilderbeek/pbdmms/cine_source.cpp:118:1: long line [size|P3] Line with 104 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/cine_source.cpp:242:1: long line [size|P3] Line with 118 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/cine_source.cpp:118:103: deep nested block [size|P3] Block depth of 6 exceeds limit of 5
/home/travis/build/richelbilderbeek/pbdmms/cine_source.cpp:218:1: deep nested block [size|P3] Block depth of 6 exceeds limit of 5
/home/travis/build/richelbilderbeek/pbdmms/cine_source.cpp:123:17: use early exits and continue [convention|P3] Use early exit/continue to simplify code and reduce indentation
/home/travis/build/richelbilderbeek/pbdmms/cine_source.cpp:217:1: high npath complexity [size|P2] NPath Complexity Number 297 exceeds limit of 200
/home/travis/build/richelbilderbeek/pbdmms/lyke_individual.cpp:89:1: long line [size|P3] Line with 110 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_individual.cpp:140:1: long line [size|P3] Line with 116 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_individual.cpp:41:1: high cyclomatic complexity [size|P2] Cyclomatic Complexity Number 13 exceeds limit of 10
/home/travis/build/richelbilderbeek/pbdmms/lyke_main.cpp:12:3: long variable name [naming|P3] Variable name with 21 characters is longer than the threshold of 20
/home/travis/build/richelbilderbeek/pbdmms/lyke_parameters.cpp:13:1: too many parameters [size|P3] Method with 11 parameters exceeds limit of 10
/home/travis/build/richelbilderbeek/pbdmms/lyke_parameters.cpp:13:1: high cyclomatic complexity [size|P2] Cyclomatic Complexity Number 12 exceeds limit of 10
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.cpp:64:1: long line [size|P3] Line with 111 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.cpp:95:1: long line [size|P3] Line with 137 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.cpp:112:1: long line [size|P3] Line with 139 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.cpp:123:1: long line [size|P3] Line with 117 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.cpp:144:1: long line [size|P3] Line with 158 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.cpp:156:1: long line [size|P3] Line with 112 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.cpp:200:1: long line [size|P3] Line with 109 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.cpp:203:1: long line [size|P3] Line with 170 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.cpp:149:5: use early exits and continue [convention|P3] Use early exit/continue to simplify code and reduce indentation
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.cpp:144:1: high cyclomatic complexity [size|P2] Cyclomatic Complexity Number 12 exceeds limit of 10
/home/travis/build/richelbilderbeek/pbdmms/lyke_utils.cpp:7:5: parameter reassignment [convention|P3] 
/home/travis/build/richelbilderbeek/pbdmms/lyke_utils.cpp:11:5: parameter reassignment [convention|P3] 
/home/travis/build/richelbilderbeek/pbdmms/jaan_utils.h:1:1: long line [size|P3] Line with 112 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/jaan_utils.h:3:1: long line [size|P3] Line with 112 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/jaan_utils.h:20:1: long line [size|P3] Line with 112 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/jaan_utils.h:50:1: long line [size|P3] Line with 155 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/jaan_utils.h:54:1: long line [size|P3] Line with 156 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.h:14:1: long line [size|P3] Line with 111 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.h:25:1: long line [size|P3] Line with 109 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.h:26:1: long line [size|P3] Line with 103 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.h:29:1: long line [size|P3] Line with 123 characters exceeds limit of 100
/home/travis/build/richelbilderbeek/pbdmms/lyke_simulation.h:37:1: long line [size|P3] Line with 101 characters exceeds limit of 100`

**Comment by JamesAndrews91** [comment]
Pretty sure I've fixed mine.

**Comment by richelbilderbeek** [comment]
With commit 562380f6bc6196d02a6ba46285fcd582bc90b0a9 I let OCLint ignore @LykeStuurman for now. I hope she will fix this soon and that she undos the change I did to `do_oclint` in that commit.

**Comment by richelbilderbeek** [comment]
Sorry @JamesAndrews91 and @christophnetz , but you are still causing broken builds throughout the project due to OCLint complaints trickling in via the `master` branch to all others. I've started ignoring @LykeStuurman , as I think this better suits her situation.

**Comment by christophnetz** [comment]
I think I'm the last one to fix his issues. I did some big changes on my branch, but tomorrow I should be able to merge again

**Comment by richelbilderbeek** [comment]
Well done @JamesAndrews91 !

**Comment by richelbilderbeek** [comment]
Well done @christophnetz !

Closing the Issue...
