### ISSUE TITLE
Run a simulation

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#122]
Running 1  simulation (4000 generations, 2000 individuals) right now.
Let's see what happens. Hopefully the PC will still be on tomorrow and it will have finished. If not, well then I have more work to do :D 

If it takes longer than 15 hours for this simulation I will have to optimize my model.

Or ask @LykeStuurman to help met get this stuff on Peregrine.

**Comment by Lumphie** [comment]
So the PC shut off :(

Any help @LykeStuurman?

**Comment by LykeStuurman** [comment]
Hi @Lumphie  and @JorikdeBoer , 
I think it would be best if I could explain Peregrine to both of you at the same time.
Tomorrow you have the TECE meeting and Thursday Peregrine will be offline until Sunday. So I suggest to meet Monday morning or after lunch. 

Cheers Lyke

**Comment by Lumphie** [comment]
monday sounds fine to me :)
