### ISSUE TITLE
git bash

### ISSUE THREAD

**Issue by LykeStuurman** [richelbilderbeek/pbdmms#127]
I do have Git Bash on my computer on the 5th floor ;) @richelbilderbeek

**Comment by richelbilderbeek** [comment]
How did you do it?

**Comment by LykeStuurman** [comment]
haha apparently. I think Joke installed it on my computer....

**Comment by richelbilderbeek** [comment]
Hmmm, so its use is limited to a non-standard (as opposite of those in the canteen) Windows computer? 

Well, everything that needed to be said, had been said :sunglasses:
