### ISSUE TITLE
Member variable should be initialized in the member initialization list. How to do so?

### ISSUE THREAD

**Issue by christophnetz** [richelbilderbeek/pbdmms#134]
Hey everyone, 
Elly and I both had some problems with vectors as class members. When declaring a vector as class member, this error message always popped up: 

/home/s3268179/pbdmms/cine_individual.h:5: error: 'individual::m_Xcoor' should be initialized in the member initialization list [-Werror=effc++ class individual

and not only for the declared vector but also for all other members. I couldn't find  a solution online, do you guys have suggestions?

**Comment by richelbilderbeek** [comment]
Sure, initialize in the initializer list, see e.g. [a page of mine](http://richelbilderbeek.nl/CppDefaultConstructor.htm).

**Comment by richelbilderbeek** [comment]
Or expained here:

```
struct MyClass
{
  MyClass(const int x) 
    : m_x{x} //this line
  {
  
  }
  private:
  int m_x;
};
```

Leave `this line` out to reproduce the error. `m_x{x}` denotes 'initialize `m_x` with `x`'.

**Comment by christophnetz** [comment]
bedankt @richelbilderbeek!
