### ISSUE TITLE
Teaching/learning Peregrine

### ISSUE THREAD

**Issue by LykeStuurman** [richelbilderbeek/pbdmms#135]
Hi guys,

Lets have a look at peregrine after the coffee break. OK?

@JorikdeBoer @Lumphie

**Comment by Lumphie** [comment]
We have a short meeting with Rampal, but right after I'm ready to learn

**Comment by richelbilderbeek** [comment]
Looks like it has been postponed to Tuesday?

**Comment by Lumphie** [comment]
Yes, tomorrow 10:30 am.

**Comment by LykeStuurman** [comment]
Hi there,

I have a meeting with Franjo today at 11.30.
I think that 30 minutes could be enough, as I also wrote down how to run on peregrine step by step.
But if you guys want to meet earlier.. I am in.

**Comment by Lumphie** [comment]
Yeah we're ready downstairs.

**Comment by LykeStuurman** [comment]
Great

**Comment by LykeStuurman** [comment]
Done!
