### ISSUE TITLE
Get elly, jobo and kewe simulations running before Christmas

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#136]
Playtime is over! 

Programming is great fun, but science is much broader. Due to this, @rsetienne assigns me the task to get your ( @EllyJet and @JorikdeBoer and @Lumphie   ) sims working before Christmas. 

This means that, from now on, I will work on your sims every morning from 9:00-12:00 (and possibly in the afternoon) with the sim owner at my side. 

Yes, we/I will make some -sometimes blunt- choices to get it to work. Yes, I will do it, instead of you. 

If you sit next to me, I think the ride will be both insightful and fun.

We start tomorrow/Tuesday morning :sunglasses:

**Comment by richelbilderbeek** [comment]
Of course, #135 has a higher precedence than this.

**Comment by richelbilderbeek** [comment]
Progress:
 * [ ] EllyJet 
 * [ ] JorikdeBoer 
 * [ ] Lumphie

**Comment by richelbilderbeek** [comment]
Simulation from @JorikdeBoer :

![fixed](https://cloud.githubusercontent.com/assets/2098230/21350010/63fb6842-c6b5-11e6-916f-d984e47e9ecb.png)

**Comment by Lumphie** [comment]
Explanation for the peak at the start?

Looking good though!

**Comment by richelbilderbeek** [comment]
`kewe`'s sim is done:

![fixed](https://cloud.githubusercontent.com/assets/2098230/21569695/8c4a1c50-cebf-11e6-871a-72771f56a4a1.png)

**Comment by richelbilderbeek** [comment]
Done more or less.
