### ISSUE TITLE
SES: survivability brackets OK?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#143]
In `calc_survivability` I see:

```
const double s{
    1.0 - (competition_intensity / (p * 2.0))
        / (gauss(ecological_trait, ecological_distribution_width))
};
```

I think it may be:

```
const double s{
    1.0 - ((competition_intensity / (p * 2.0))
        / (gauss(ecological_trait, ecological_distribution_width)))
};
```

I'd love to see the equations of van Doorn & Weissing 2002 about this equation.

I assume the brackets are OK for now.

**Comment by richelbilderbeek** [comment]
`kewe_calc_survivability` is the test to check these equations in detail.

**Comment by Lumphie** [comment]
![schermafbeelding 2016-12-20 om 17 12 46](https://cloud.githubusercontent.com/assets/21882358/21358051/c89d4eb0-c6d7-11e6-98d9-6f878004fe2f.png)

**Comment by Lumphie** [comment]
This is for mortality m. Survivabilty = 1 - m.

Gamma has been replaced by population size.
Compiler follows math rules right? * and / before + and - ?
You can add brackets to be 100% sure.

**Comment by richelbilderbeek** [comment]
Awesome! Compilers do follow rules, but not necessarily the ones we expect. I will add those brackets to be sure :+1:

**Comment by richelbilderbeek** [comment]
I've added a `calc_mortality` function, that replaces `s=1-(something) / (something) / (something)` (or something like that) by `s=1-m(something)`.

**Comment by richelbilderbeek** [comment]
AFAICS, looks great, thus close this Issue
