### ISSUE TITLE
Problems of the current BDM model

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#145]
There are in my opinion still a few problems in the current version of the BDM model:
- The model doesn't work with low population sizes of 10 (probably because it works with a population of only 1 individual and picks the same mother and father for infinity).
- I think the model also includes incompatible genotypes if it counts the number of good species groups, because the count_good_species function comes after the mutation functions.
- I don't understand why there are two different get_results functions

**Comment by richelbilderbeek** [comment]
Acknowledged first point, this combination causes an infinite run:

![issue](https://cloud.githubusercontent.com/assets/2098230/21425526/ea5319cc-c849-11e6-9fa6-e71f603ce848.png)

**Comment by richelbilderbeek** [comment]
Second point: I think these hopeful monsters are a feature.
Third point: referred to [Avoid duplication in const and non-const member functions](http://richelbilderbeek.nl/CppAvoidDuplicationInConstAndNonConstMemberFunctions.htm).

**Comment by richelbilderbeek** [comment]
Program will throw, maybe crash, when this happens :see_no_evil:
