### ISSUE TITLE
Read report

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#150]
https://github.com/richelbilderbeek/pbdmms/blob/master/Documentation/kewe_verslag_v2_1.pdf

**Comment by JorikdeBoer** [comment]
Mine is here if @richelbilderbeek hasn't found it already:
https://github.com/richelbilderbeek/jobo_portfolio/blob/master/Concept%20Report%20Master%20project%20BDM-model%20Jorik.pdf

**Comment by richelbilderbeek** [comment]
Awesome! I will read both before Monday.

**Comment by richelbilderbeek** [comment]
Feedback has been posted to the repo's I found the reports in. I can hand these in paper on Monday as well.
