### ISSUE TITLE
SES: use costly ornaments

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#153]
There must be divergent selection of male sexual trait.

@Lumphie : can you recall the last version that has sympatric speciation? It is also OK if it is in another GitHub. 

Maybe `git log --pretty=oneline` is helpful :sunglasses: (I need the long string at the left, e.g. 7acdd51ceb06cf26a562fba25d9bfdcff1ad2aea)

**Comment by Lumphie** [comment]
https://github.com/Lumphie/CCPPP2016/blob/master/adapspc4.cpp

As far as I can recall; this is the last version that had sympatric speciation. (Version for the cpp course)

**Comment by richelbilderbeek** [comment]
Eco traits:

![sado](https://cloud.githubusercontent.com/assets/2098230/21471023/d23be01c-caa1-11e6-82bc-cf0f884c715f.png)

Fem prefs:

![fem_prefs](https://cloud.githubusercontent.com/assets/2098230/21471024/d97979e8-caa1-11e6-8a85-a2c7fa11d238.png)

Male sex traits:

![male_traits](https://cloud.githubusercontent.com/assets/2098230/21471025/dd1bb44e-caa1-11e6-8578-c1bcfbcefb42.png)

**Comment by richelbilderbeek** [comment]
Used parameter from article:

Ecological traits:

![eco_traits](https://cloud.githubusercontent.com/assets/2098230/21472108/85ab088a-caca-11e6-890f-323b59e19da6.png)

Female preferences:

![fem_prefs](https://cloud.githubusercontent.com/assets/2098230/21472107/85a8fa86-caca-11e6-9856-f6484dc282b7.png)

Male traits:

![male_traits](https://cloud.githubusercontent.com/assets/2098230/21472109/85ad9424-caca-11e6-94ea-f50a1dabf005.png)

**Comment by richelbilderbeek** [comment]
Implemented the original article in the `sado` namespace.
