### ISSUE TITLE
kewe: has_bimodal_eco_types bug

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#160]
When I look [here](https://github.com/richelbilderbeek/pbdmms/blob/ed0e7f16ec83807f7d8db32cd15b95e71111d400/kewe_results.cpp#L155) I see:

```
bool kewe::has_bimodal_eco_types(const results& result)
{
  assert(!result.m_ecological_trait.empty());
  count_borders(result.m_ecological_trait.back());
  return false;
}
```

Note how this function *always* returns false.

It should be something like:

```
bool kewe::has_bimodal_eco_types(const results& result)
{
  assert(!result.m_ecological_trait.empty());
  return count_borders(result.m_ecological_trait.back()) > [some_value];
}
```

where `[some_value]` is some value.

@Lumphie : what would that value be? 0, 1, 2 or 3?

**Comment by Lumphie** [comment]
Whoops. Count_borders >= 3 because 2 borders = 1 lineage.

**Comment by richelbilderbeek** [comment]
Thanks, fixed it!
