### ISSUE TITLE
sado: overlapping generations indeed

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#165]
The `sado` sim has stated to have overlapping generations. What is remarkable about this, is that one 'generation' parents can possibly mate with their grand-grand-grand-kid.

This is the function, shown for reference:

```
void sado::iterate(population pop, const parameters& p)
{
  for(int t=0;t<=endtime;++t)
  {
    if(pop.empty()) return;
    if(t%outputfreq==0)
    {
      output(pop, t, pop.size());
    }
    for(int k=0;k<static_cast<int>(pop.size());++k)
    {
      if(pop.empty())
      {
        return;
      }
      const int index{pick_random_individual_index(pop.size())};
      const indiv mother{pop[index]};
      const double xi=mother.get_x();
      const double pi=mother.get_p();
      const double qi=mother.get_q();
      const double comp{calc_comp(pop, xi)};
      if(Uniform()<(1.0-((comp*c)/gauss(xi,sk)))*(0.5+(0.5*gauss(qi,sq))))
      {
        //The attractivenesses you have with pi and xi
        std::vector<double> as{get_attractivenesses(pop, pi, xi)};
        //Unattracted to yourself
        as[index] = 0.0;
        //Get kids
        const auto kids = create_kids(pop, mother, as);
        for (auto kid: kids)
        {
          pop.push_back(kid);
        }

      }
      if (p.get_erasure() == erasure_method::erase)
      {
        assert(index < static_cast<int>(pop.size()));
        pop.erase(std::begin(pop) + index);
      }
      else
      {
        assert(index < static_cast<int>(pop.size()));
        std::swap(pop[index], pop.back());
        pop.pop_back();
      }
    }
  }
}
```

Here is the function with focal points:

```
void sado::iterate(population pop, const parameters& p)
{
  for(int t=0;t<=endtime;++t)
  {
    for(int k=0;k<static_cast<int>(pop.size());++k)
    {
      const int index{pick_random_individual_index(pop.size())}; //[1]
      if(Uniform()<(1.0-((comp*c)/gauss(xi,sk)))*(0.5+(0.5*gauss(qi,sq))))
      {
        const auto kids = create_kids(pop, mother, as);
        for (auto kid: kids)
        {
          pop.push_back(kid); // [3]
        }
      }
      pop.erase(std::begin(pop) + index); //[2]
    }
  }
}
```

An individual is picked at a random index `index` [1].
When that individual does or does not produce offspring, she dies [2]. 
The offspring is put at the back of the vector [3].
The father is chosen from the current population, based on his attractiveness.

This makes the following situation possible:
 * Assume a population of two, with individuals names `Ann` and `Bert`
 * `Ann` is chosen at random to reproduce. The father will be `Bert`. Her kids are `Clide` and `Dave`, `Eddy` and `Finn`
 * `Ann` dies
 * `Bert` is chosen at random to reproduce. The father will be his son `Clide`. His only kid will be `Ginny`.
 * `Bert` dies
 * `Clide` is chosen at random to reproduce. The father will be his niece `Ginny`. His only kid is `Harry`.
 * `Clide` dies
 * `Dave` is chosen at random to reproduce. The father will be his grand-niece `Ginny`. His only kid is `Isaac`.
 * `Dave` dies

Now Dave can already mate with his grand-grand-niece `Ginny`.

**Comment by richelbilderbeek** [comment]
Or

```
A x B (unrelated) -> C D E F
A dies
B x C (father-son) -> G H I J
B dies
C x G (one generation difference) -> K L M N
C dies
D x N (two generations difference) -> O P Q R
D dies
E x R (three generations difference) -> S T U V
E dies
F x V (four generations difference) -> W X Y Z
F dies
G x Z (four generations difference) -> a b c d
G dies
H x d (five generations difference) -> a b c d
H dies
[at infinitum]
```

**Comment by richelbilderbeek** [comment]
@Lumphie I guess you already knew?

**Comment by Lumphie** [comment]
Yes I told you 2 weeks ago, but you said this wasn't too big of an issue while I thought that it was important. Because as long as an individual is fit enough it will stay in the population until it finds someone to mate

**Comment by richelbilderbeek** [comment]
> Because as long as an individual is fit enough it will stay in the population until it finds someone to mate

I do disagree on this. It will die if not fit enough.

**Comment by richelbilderbeek** [comment]
My point is that it is a weird implementation. It is just not overlapping generations, but something like 'complex multi-generational' generations.

**Comment by Lumphie** [comment]
> Because **as long as an individual is fit enough** it will stay in the population until it finds someone to mate


> I do disagree on this. **It will die if not fit enough.**

That's what I'm saying.

There is an ETA paramater in there somewhere that gives the fit enough females a chance to not mate at all and just go in to the next generation.

**Comment by Lumphie** [comment]
And yes it's indeed complex. There should be an age variable in there somewhere so they have a higher chance of dying after a few generations.

**Comment by richelbilderbeek** [comment]
> Because as long as an individual is fit enough it will stay in the population until it finds someone to mate

What do you mean exactly? Is `an individual` a male or female or both? How do you define `fit enough`?

Because now I'd disagree: 

 * for individuals picked as mother: all individuals -independent of fitness- that get picked for the role of (potential) mother will always die
 * for individiduals picked as a mate: these are only chosen on their attractivenesses. 

Because (approximately) every generation of (dynamic) size `n`, there are `n` mothers being picked, all individuals are expected to live in one generation. Sure, there is a chance an individual can escape being picked as a mother and die, but this is pure chance and has nothing to do with fitness.

> There is an eta parameter in there somewhere that gives the fit enough females a chance to not mate at all and just go in to the next generation.

Incorrect. The `eta` does not allow a picked female to stay alive (see code). The `eta` just makes her more picky in choosing a mate. Which makes `eta` an unnatural parameter: it only allows for not to produce offspring if it is your last chance to do so. Selection will make `eta` go to zero as soon as possible.

**Comment by Lumphie** [comment]
Oh I see. I read that wrong. I read in his paper about the eta and imagined it working that way (females does not find an attractive mate so it will wait till the next generation).

But then Eta does not do what they say in their paper.

They mention that eta becomes higher when searching for a mate is costly. But if searching for a mate is costly then why die without mating?

So yes I completely agree that this is not just overlapping generations, but way more complex. Apparently this complex mechanism makes sympatric speciation possible?

**Comment by richelbilderbeek** [comment]
Thanks for your thoughts!

The paper does not match the code in at least one place (see #163, which has been rebranded a feature of the model), this may be another such instance...

**Comment by richelbilderbeek** [comment]
I predict @rsetienne does not want us to implement generations in that ... peculiar ... fashion.

**Comment by Lumphie** [comment]
I am willing to bet a beer on that.

**Comment by richelbilderbeek** [comment]
I disagree with myself here: with overlapping generations, it is *always* a feature that different generations can possibly mate.

If it does match with the article is still a point of concern.

**Comment by richelbilderbeek** [comment]
A non-zero `eta` allows for having a selection on the female preference (to match the male trait). Albeit biologically peculiar, I agree it may help getting speciation.

**Comment by richelbilderbeek** [comment]
## Overlapping generations

![1](https://cloud.githubusercontent.com/assets/2098230/21553247/a19f2d88-ce07-11e6-9871-fd6bf18afe68.png)
![2](https://cloud.githubusercontent.com/assets/2098230/21553248/a6c13e1e-ce07-11e6-8d87-cfd83f54adba.png)
![3](https://cloud.githubusercontent.com/assets/2098230/21553255/ac41d59c-ce07-11e6-83a0-2ff369554d7b.png)
![4](https://cloud.githubusercontent.com/assets/2098230/21553253/ac40f5dc-ce07-11e6-8c15-0112a4ccf82d.png)

## Seperate generations

![2_1](https://cloud.githubusercontent.com/assets/2098230/21553249/ac194f8c-ce07-11e6-8dd6-61ff487dd3a5.png)
![2_2](https://cloud.githubusercontent.com/assets/2098230/21553251/ac2f1362-ce07-11e6-9c60-4f4e013eed0b.png)
![2_3](https://cloud.githubusercontent.com/assets/2098230/21553252/ac3e670e-ce07-11e6-9333-d37bba4d3c53.png)
![2_4](https://cloud.githubusercontent.com/assets/2098230/21553254/ac418344-ce07-11e6-8aea-3d5934b533c7.png)

**Comment by richelbilderbeek** [comment]
Can now pick both ways.
