### ISSUE TITLE
The path of the midterm evaluation

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#178]
Progress says that my midterm evaluation has to be returned to the administration. I think I understood from Kees that this difficult task has to be done by the supervisor of the student. If the administration is back from their holidays, maybe @richelbilderbeek is able to accomplish the task to bring the midterm evaluation form to the administration?

**Comment by Lumphie** [comment]
Can confirm, progress tells me to return my midterm evaluation as well.
Administration is inconsistent. Sometimes they allow students to return it, sometimes they don't. Better be safe than sorry.

**Comment by richelbilderbeek** [comment]
Ah, I am partly to blame: I've put @Lumphie's evaluation in @rsetienne's mailbox just this morning. 

OTOH, @JorikdeBoer's has been signed already a long time ago and AFAIK processed by @rsetienne.

**Comment by JorikdeBoer** [comment]
Progress still says that my midterm evaluation has to be returned to the administration.
![screenshot - 01162017 - 10 29 49 am](https://cloud.githubusercontent.com/assets/22076213/21977552/e518100c-dbd6-11e6-82c5-d4fff1af1447.png)

**Comment by JorikdeBoer** [comment]
The path of the midterm evaluation is completed!!!
