### ISSUE TITLE
Teach git on Friday January 20th

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#181]
From Michael Fontaine:

```
I hope you are still willing to contribute to the course of Bioinformatics with an introduction to the use of GIT version control (as you did last year).
For planning reason, I decided to keep the same structure as last year. 
Thus, would you be available to give the GIT introduction next week on Friday (20/01), in the morning (from 9:30 to 12:30)?
The room will be LB 5173.0176 (if I can trust the room scheduler…)
```

Anybody volunteers to be one or more of these?

 * teaching assistant
 * involved in the lecture its content 
 * the lecturer

Let me know!

 * [ ] @LykeStuurman 
 * [ ] @Lumphie 
 * [ ] @JorikdeBoer 
 * [ ] @EllyJet (I know this is your last day)
 * [ ] @christophnetz 
 * [ ] @JamesAndrews91

**Comment by christophnetz** [comment]
Hey Richel,
I'm actually enrolled for the course, but I think I could still contribute, preferably as teaching assistant or being involved in the lecture content.

See you tomorrow!

**Comment by Lumphie** [comment]
Can be any of the three as long as I can go on 12:30

**Comment by EllyJet** [comment]
Final presentation has been moved to that moment

**Comment by Lumphie** [comment]
The course is in English?
Are we teaching in English or Dutch @richelbilderbeek?

**Comment by richelbilderbeek** [comment]
We are teaching in English. I saw your work on the fairytale, great! 

Superfluously, I hope you'll plan some time for @JorikdeBoer to lecture at least something, and you will have me, Jorik and @christophnetz to assist. 

We'll discuss the lesson plan tomorrow. It will be fun :-)

**Comment by Lumphie** [comment]
Will work on lesson plan next. Was testing the merge conflicts and possible problems students could get.

**Comment by JorikdeBoer** [comment]
We did it!
