### ISSUE TITLE
elly: conclude_n_missing_species incomplete

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#184]
In the end of the `elly::conclude_n_missing_species` function, there was nothing.

To have sometinng returned, I've added:

```
throw std::logic_error("No idea what EllyJet wanted here");
```

**Comment by richelbilderbeek** [comment]
Marked failing tests with `FIX_ISSUE_184`

**Comment by richelbilderbeek** [comment]
Weird, the test `elly_convert_reality` passes, the test `elly_convert_ideal` fails...

**Comment by richelbilderbeek** [comment]
I let it return zero for now, but I hope @EllyJet takes a look at it.

**Comment by EllyJet** [comment]
conclude_n_missing_species deleted, as missing species are never used
