### ISSUE TITLE
elly: document elly_collect_branching_times_two_branches_1

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#192]
What does this mean?

```
         a          d
         |          |
      +--+--+       |
      |     |       |
      b     c       d

      d stays on the mainland,
      a migrates and diversifies
```

It is unclear to me what happens when and where. Reading the code did not resolve this. Please document in more detail.

**Comment by EllyJet** [comment]
It is now documented better,
`  /*    Mainland            Island
      +----+
      d    a
      |    |-   -   -   -   -   -a
      |    +<anagenesis          +<anagenesis
      |    c                     b
      |    |-   -   -   -   c    |
      |    |                |    |
      d    c                c    b

      d stays on the mainland,
      a migrates and diversifies
      there should be one branching times, time of colonization for a, and time of birth
      of species b.
   */`
is it readable now?
