### ISSUE TITLE
kewe: find new model OR fix sado so I can trust it again

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#193]
Not sure if I want to switch to another model, but I said I wanted to look for a new model this weekend.
Will decide Tuesday (I think?).

**Comment by Lumphie** [comment]
Drossel B. and McKane A. "Competitive Speciation in Quantitative Genetic Models"
Seems to be a model with an individual based mechanism

> As with many other authors, we characterize
the population by the distribution p(z, t) of
a quantitative trait, z in generation t, such as
body size or beak size. In common with the
literature on character displacement, we introduce
the carrying capacity K(z), which is the
number of individuals with trait z that the environment
can support if no individuals with other
trait values are present.

**Comment by Lumphie** [comment]
Of course I can look at this one: Dieckmann & Doebeli "On the origin of species by sympatric speciation"

**Comment by Lumphie** [comment]
Oh that one is not individual based?

**Comment by richelbilderbeek** [comment]
AFAIK,  Dieckmann & Doebeli is individual-based. It does leave out the exact mechanism of sympatric speciation, unlike the Van Doorn approach with male trait and female preference.

**Comment by Lumphie** [comment]
I deleted that. It is indeed individual-based, but they started their method with an analytical approach. then later they tested that approach with the individual-based model.
It uses a set of ecological traits, a set of mating probabilities trait and a set of marker traits.

**Comment by Lumphie** [comment]
Turner G.F. and Burrows M.T. "A model of sympatric speciation by sexual selection"

Individual-based
Seperate generations
Fixed population size

>  Female mortality was random with
 respect to genotype, and was set to equal male
 mortality to maintain an approximately constant 1:1
 sex ratio. Randomly selected surviving females mated
 once, producing two offspring, until the number of
 offspring produced balanced adult mortality, main-
 taining a constant total population size N

**Comment by Lumphie** [comment]
That last one does not have seperate generations

>  Overlap-
 ping generations were assume

**Comment by Lumphie** [comment]
Ran model and compared to article. First part is skipped because, as mentioned, I don't need it for my research question. @richelbilderbeek 

Ecological types don't match at all.

male trait and female preference do match kinda.

![sado-model-vs-article](https://cloud.githubusercontent.com/assets/21882358/21985884/1ee65b42-dbfd-11e6-87ec-46736461a0f2.png)

**Comment by Lumphie** [comment]
![image](https://cloud.githubusercontent.com/assets/21882358/21987441/d85c5670-dc03-11e6-8d9d-1864c0420d8b.png)

Hmm. @richelbilderbeek

**Comment by Lumphie** [comment]
![image](https://cloud.githubusercontent.com/assets/21882358/21987663/ba99e89a-dc04-11e6-907c-68709db385f2.png)

@richelbilderbeek histogram bars 20 times enlarged

**Comment by Lumphie** [comment]
fixed population size is using constant c. That's not supposed to happen right, because population size is fixed and c is a constant to make competition stronger or weaker to get some population size.

**Comment by Lumphie** [comment]
![image](https://cloud.githubusercontent.com/assets/21882358/21988843/f5523ee8-dc08-11e6-966f-b2b2e4828d16.png)


So close

**Comment by Lumphie** [comment]
Not a seed thing. Tried several seeds including, but not limited by: 123 122 121 120 42 314 31415926535979323846264338297 456564

**Comment by Lumphie** [comment]
Some seeds have branching after a few generations, but then flow back to 1 branch.

**Comment by Lumphie** [comment]
Not enough time to change model. Will just have to deal with it :-1:
