### ISSUE TITLE
elly:todo try to replicate results from article

### ISSUE THREAD

**Issue by EllyJet** [richelbilderbeek/pbdmms#199]
Made parameter_no_mainland_extcinction,
there is no turnover, maybe good to compare results from this parameter file to article results.
also could be used as control, if comparable

**Comment by richelbilderbeek** [comment]
I'd love to do that! There will be need to prioritize though and I am unsure if this is a priority.

**Comment by EllyJet** [comment]
I agree, it is not a priority. Let's see how far we get

**Comment by richelbilderbeek** [comment]
Too bad, project has been closed. This Issue follows.
