### ISSUE TITLE
sado: pedigree

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#204]
I think we need boost graph for this right?

Link all parents with their children.
Group individuals in species
Link generations of species
Make phylogeny
???
Profit

**Comment by richelbilderbeek** [comment]
We do.

**Comment by richelbilderbeek** [comment]
I think this has been done now. Use `sado::create_reconstructed` on a species graph, then `sado::to_newick` to get a newick,  then `sado::calc_max_likelihood` on that Newick.
