### ISSUE TITLE
add nltt to jkr_experiment.h

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#206]
I suggest to add the line: 

  save_nltt_plot(get_results(s), get_nltt_plot_filename(p));

to jkr_experiment.h, because we ( @Lumphie, @richelbilderbeek)   all want to get nltt's!

**Comment by richelbilderbeek** [comment]
I'll follow

**Comment by Lumphie** [comment]
Fine with this. Just not what I'm working on right now, so it'll take a while before I get there.

**Comment by JorikdeBoer** [comment]
It has been done and there is no turning back.

**Comment by Lumphie** [comment]
Of course there is a way back. We're using git
