### ISSUE TITLE
sado / kewe: (parameter) SPACE EXPLORATION

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#207]
I ran 100 simulations of the sado model (used swap, lut and no bug to make it quicker)

All parameters were the same as the sado article except for sigma c, which started at 0.01 (first simulation) and ended at 1.0 (100th simulation)

I created this wonderful GIF of the ecological type.

![Sigma_C from 0.01 - 1](https://github.com/richelbilderbeek/pbdmms/blob/master/Screenshots/www.GIFCreator.me_QXxJJl.gif?raw=true)

Female preference is still uploading.

Will make more simulations that increase other parameters and see what works.

**Comment by Lumphie** [comment]
Ecotype branching as in the article happens somewhere around 0.6-0.7

**Comment by Lumphie** [comment]
Female preference with increasing sigma c.
Not really interesting.

![female preference with increasing sigma c] (https://github.com/richelbilderbeek/pbdmms/blob/master/Screenshots/sigmac_on_female_pref.gif?raw=true)

**Comment by Lumphie** [comment]
runs with sigma e are just in. Not really interesting. 

Best around 0.5-0.6 probably.

**Comment by Lumphie** [comment]
On peregrine now: sk from 0.02 - 2.0 (Simulations12)
sm from 0.005 - 0.5 (simulations_sm)

**Comment by Lumphie** [comment]
The queue is taking too long. Will check back tomorrow!

**Comment by Lumphie** [comment]
Higher sigma k => more and more stable branching for ecotype.
Maybe more branching on sexual traits, but not a very high effect.

gif is incoming

**Comment by Lumphie** [comment]
![sigmak_on_eco_type](https://cloud.githubusercontent.com/assets/21882358/22324188/0b84455c-e3a8-11e6-98c9-4d8d7210000c.gif)

As expected. Biggerresource distribution gives more room for branching.

Will stay with 1.2 sk for now with the knowledge that I can increase it whenever needed.

No (or small) effect on sexual traits

**Comment by Lumphie** [comment]
Something went wrong with the sigma_m simulations. Will rerun them after sigma_q is done.

**Comment by Lumphie** [comment]
No fancy gifs of sigma Q.

Nothing interesting. We'll keep it at 1

**Comment by Lumphie** [comment]
Nothing interesting in sigma_m
I keep it at 0.2

Will run multiple simulations of

sm 0.2
sq 1.0
sk 1.2
se 0.5
sc 0.6

**Comment by Lumphie** [comment]
Okay lets just use the same exploration techniques for separate generations

**Comment by Lumphie** [comment]
So many problems... euhm challenges. 

Forgot to scale c to the population size. It was stalled at 1700 individuals. It should run now with scaled c

**Comment by Lumphie** [comment]
Note to all:
All computers reset at 22:30.

Something I just found out.

**Comment by Lumphie** [comment]
Increasing C increases eco type branching with seperate generations. Now I just need a way to increase the sexual traits branching

**Comment by Lumphie** [comment]
![sep_c_on_eco_type](https://cloud.githubusercontent.com/assets/21882358/22367306/284f18c2-e481-11e6-882e-3d7e37c9d646.gif)

Okay another one, because they are so pretty.

Increasing c (the constant) increases the chance of branching, but it also increases the chance of nobody surviving.

**Comment by Lumphie** [comment]
![sep_c_female_pref](https://cloud.githubusercontent.com/assets/21882358/22367433/d61dd86c-e481-11e6-86b3-86669b8d8aec.gif)

And this is female preference. 

Right now increasing population size is running and sigma m

**Comment by Lumphie** [comment]
increasing sm to 1.0 gets very close to branching on female preference, but somehow not on male trait...

Which is of course because making sm higher lowers selection pressure on the outsiders of female preference, but not on the outsiders of male trait.

**Comment by Lumphie** [comment]
![sep_sm_fem_pref](https://cloud.githubusercontent.com/assets/21882358/22370165/56d78738-e490-11e6-89f8-8587c790aceb.gif)

Female preference for an increasing sm.

**Comment by Lumphie** [comment]
300 simulations running right now!

different population sizes
sq
and 100 random simulations with the following parameters

sc 0.6
sk 2.0
sv 0.02
se 3.0 (!!!)
pop 10,000 (!)
c 0.000005
sm 1.0 (!)
sq 1.0 (I expect this should be enough)

Only time will tell what'll happen.

**Comment by Lumphie** [comment]
Okay so the 100 random simulations are in. 
Not looking like it's enough.

In order:

Eco_trait
Fem_pref
Male_trait

![eco_traits1](https://cloud.githubusercontent.com/assets/21882358/22416749/ba8fbd8a-e6d0-11e6-987f-74809a42441a.png)


![fem_prefs1](https://cloud.githubusercontent.com/assets/21882358/22416754/c1a883fe-e6d0-11e6-9eb6-7a8550b0ba87.png)

![male_traits1](https://cloud.githubusercontent.com/assets/21882358/22416758/c6548394-e6d0-11e6-8181-3b977d8115aa.png)

**Comment by Lumphie** [comment]
Can't get the male trait to follow the females. sq might be too high.

Eco type is not getting big enough, so higher Sk and probably a higher Sc (to get the branching hopefully)

**Comment by Lumphie** [comment]
Or maybe increase c a bit.

**Comment by Lumphie** [comment]
Now running:

sc 1.2
sk 4.0
sv 0.02
se 3.0 (!!!)
pop 10,000 (!)
c 0.00005
sm 1.0 (!)
sq 0.5

**Comment by Lumphie** [comment]
Also

sc 0.6
sv 0.02
se 3.0
pop0 1000
c 0.001
sm 1.0
sq 0.6
type0 0 0 0' > kewe_sado_parameters${i}.txt

echo "seed ${i}" >> kewe_sado_parameters${i}.txt

sk=$(printf '%s * %s\n' "$i" "0.05" | bc)
echo "sk $sk" >> kewe_sado_parameters${i}.txt

Increasing sk (0.05 -> 5.0 with steps of 0.05)

**Comment by Lumphie** [comment]
If eco_trait branches anyway a low se should let the sexual traits follow.

**Comment by Lumphie** [comment]
So I have to get ecotype to branch first.

Starting at sk this time.

sm 0.2
sq 1.0
sk 1.2
se 0.5
sc 0.6

These gave branching at both ecotype and sexual trait in the overlapping generations. 
Running increase sk now (starting at 0.05, ending at 5.0)

**Comment by Lumphie** [comment]
increasing c looks promising:

ecotype
fempref
maletrait
![eco_traits](https://cloud.githubusercontent.com/assets/21882358/22426089/40ace91a-e6fe-11e6-8d17-49078e55eeb2.png)
![fem_prefs](https://cloud.githubusercontent.com/assets/21882358/22426088/40a8a0e4-e6fe-11e6-8687-3f3cc9d05b67.png)
![male_traits](https://cloud.githubusercontent.com/assets/21882358/22426087/40a89612-e6fe-11e6-94cc-56527afe26c7.png)

**Comment by Lumphie** [comment]
ONE DAY WE WILL FIND THOSE PARAMETERS! BUT IT IS NOT THIS DAY! THIS DAY WE USER PEREGRINE. FOR SADOOOOOOOOOO!!!!

**Comment by Lumphie** [comment]
Running simulation for 40.000 generations for around 10.000 individuals.

Lets see what happens.

**Comment by Lumphie** [comment]
Simulation got stuck because population size kept increasing.
Increased c and ran it again.

It's not at generation 20.000 so halfway! :smile: 14.000 individuals now.

**Comment by Lumphie** [comment]
Damnit 
![eco_traits](https://cloud.githubusercontent.com/assets/21882358/22639501/9ed5d2f4-ec4e-11e6-9770-b926034b7833.png)
![fem_prefs](https://cloud.githubusercontent.com/assets/21882358/22639500/9ed5b99a-ec4e-11e6-8705-6acaf09c7e19.png)
![male_traits](https://cloud.githubusercontent.com/assets/21882358/22639499/9ed5a22a-ec4e-11e6-8376-eab6ecc00439.png)

**Comment by Lumphie** [comment]
I think I found some parameters which have speciation.
Have to get the histogramwidths right though.

**Comment by richelbilderbeek** [comment]
It has been done.
