### ISSUE TITLE
Finding bugs and maybe run new simulation

### ISSUE THREAD

**Issue by EllyJet** [richelbilderbeek/pbdmms#212]
Just talked to Rampal, he suggested that I find the bugs and repair them so I can run one last time. Maybe with less parameter settings. 
If the bugs can not be found and repaired today, I'll leave it as is

**Comment by EllyJet** [comment]
So one of the problems we figured out were branching times.
if branching time = 0.0 it should have been equal to crown age, in this case 4. branching time 1 should have been 4-1 =3  etc.

**Comment by richelbilderbeek** [comment]
I'll open up the DAISIE_1_3 GitHub for ya.

**Comment by richelbilderbeek** [comment]
Set up the pipeline for another run. I cannot help you find the bug today, so instead: 'Go Elles!'

**Comment by EllyJet** [comment]
Well,  I tried.

**Comment by EllyJet** [comment]
Branching times should be corrected now.  As for the other bug,  one test fails but I can't pinpoint exactly where it goes wrong.

**Comment by richelbilderbeek** [comment]
I undid this, as it disrupts many other tests. Reverted to our time unit of 'time since stem age, in million years'

Documented in [Documentation/elly.md](Documentation/elly.md). Reopen this Issue when this needs to be  solved.
