### ISSUE TITLE
jobo: Peregrine problems

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#213]
Peregrine says:

./jobo_build_peregrine: line 19: ./jobo_peregrine: No such file or directory

but jobo_peregrine.pro is available.
What's the problem? @richelbilderbeek

**Comment by Lumphie** [comment]
It's asking doe jobo_peregrine, and you have jobo_peregrine.pro. Change name of jobo_peregrine.pro to jobo_peregrine

**Comment by Lumphie** [comment]
aaking for*

**Comment by richelbilderbeek** [comment]
Ah:

 * `jobo_peregrine`  is the name of an executable
 * `jobo_peregrine.pro` is the name of a project file

Running

```
qmake jobo_peregrine.pro
make
```

creates the executable `jobo_peregrine`.

Does that help?

**Comment by JorikdeBoer** [comment]
i added qmake to my build_peregrine file, but still the same error

./jobo_build_peregrine: line 20: ./jobo_peregrine: No such file or directory

**Comment by richelbilderbeek** [comment]
What is the output of ./jobo_build_peregrine`? From your words, I'd guess that compilation fails, thus no executable is created.

**Comment by richelbilderbeek** [comment]
I got it to work, just (run and) imitate `./jobo_jobscript_episode_XXVI.sh`.
