### ISSUE TITLE
jobo: pbd parameter settings

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#214]
Is the following parameter setting useful as test parameter setting @richelbilderbeek ?,
because the pbd.pro simulation is taking forever to create a .csv file.

 birth_good {0.5};
 birth_incipient {0.5};
 completion {0.1};
 death_good {0.1};
 death_incipient {0.1};
 time {100};
 seed {42};

**Comment by richelbilderbeek** [comment]
I'd say yes. When in doubt: reduce `time`.

**Comment by JorikdeBoer** [comment]
It seems to work with a time of 10
