### ISSUE TITLE
pbd: nLTT must scale to highest LTT

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#223]
Now, when an nLTT is constructed from an LTT, it is assumed the last number lineages is the maximum number of lineages. This is true only for LTTs from reconstructed trees.

 * [x] Write test with non-monotonous LTT
 * [x] Fix code
 * [x] Clean up

**Comment by JorikdeBoer** [comment]
Code already took this into account. Well done @richelbilderbeek !
