### ISSUE TITLE
jaan: building on Windows

### ISSUE THREAD

**Issue by JamesAndrews91** [richelbilderbeek/pbdmms#226]
I got a new bed but set it up wrong so I can barely sit up let alone walk about right now so I'm working from home. 

I was trying to get the model to run at home and Richel, you had suggested if g++-5 doesn't work, replace it with g++. I did that and now I'm getting:

boost/test/unit_test.hpp: No such file or directory

as the issue. I tried googling and it seems to be suggesting I don't have the boost libraries but I thought the g++ issue was that I needed minGW which wasn't true.

Thanks for your help!

**Comment by richelbilderbeek** [comment]
Simple, add

```
LIBS += -lboost_unit_test_framework
```

to your .pro file

**Comment by richelbilderbeek** [comment]
Perhaps as an additional answer: you may simply need to install boost:

```
sudo apt-get install libboost-all-dev
```

**Comment by JamesAndrews91** [comment]
Thanks Richel!

**Comment by richelbilderbeek** [comment]
Does it work?

**Comment by JamesAndrews91** [comment]
Need to install boost, will close the issue if it works.

**Comment by JamesAndrews91** [comment]
I downloaded and extracted the boost files to C:\Program Files\boost\boost_1_63_0

Do I need to tell qt where to find the boost directory, if so how?

**Comment by richelbilderbeek** [comment]
Ouch, I do not know Windows well, but I see from a Windows user [here](https://github.com/CarmenIJsebaart/Sneek/blob/master/Sneek.pro), that she added:

```
INCLUDEPATH += C:/Boost/include
INCLUDEPATH += C:/Boost
LIBS += C:/Boost/stage/lib/libboost_filesystem-mgw49-mt-1_59.a
LIBS += C:/Boost/stage/lib/libboost_system-mgw49-mt-d-1_59.a
```

Modify those paths and you may be ready to go.

**Comment by JamesAndrews91** [comment]
That didn't work but I found [this](http://stackoverflow.com/questions/16998326/how-do-i-use-the-boost-libraries-in-a-qmake-project) and so am going to see if that works. Will let you know if I find the solution. Thanks for your help.

**Comment by richelbilderbeek** [comment]
Or maybe [this helps](http://richelbilderbeek.nl/CppBoostInstall.htm)

**Comment by richelbilderbeek** [comment]
Iff you get stuck, you could let me work on your laptop (currently I am at home, close the central station, this may be closer by than at Zernike)

**Comment by JamesAndrews91** [comment]
I live just off campus so not really. No matter, I brought the laptop into campus so I could work on that problem while I run the simulations I want to run before my  meeting today. I'll continue bringing it in until I've got it running on the laptop.

**Comment by JamesAndrews91** [comment]
After extracting the boost library as you show at your link I get a lot of -Werror=effc++ errors for the boost library. Googling found [this link](http://stackoverflow.com/questions/1564937/gcc-warning-will-be-initialized-after) which suggested adding QMAKE_CXXFLAGS_WARN_ON += -Wno-reorder but this did not remove the errors after inserting into the project file. That's how far I've got now.

**Comment by richelbilderbeek** [comment]
The flag `-Weffc++` does give a lot of noise. Sometimes `-Weffc++` is not worth the effort.

I try to keep it in when I can, often turning it off when including boost headers.

See http://richelbilderbeek.nl/CppWeffcpp.htm for how I do so :-)

**Comment by JamesAndrews91** [comment]
I've got it to quit complaining about -Weffc++ and so the next issue is the ubsan library. It can't find it. Is this a separate install or do I need to point to it in my PATH?

**Comment by richelbilderbeek** [comment]
It's a separate install.

When working on Windows, I suggest to remove it from the `.pro` files by doing:

From:

```
# USBAN stuff
```

To:

```
unix:!mac {

  # UBSAN stuff
}
```

**Comment by JamesAndrews91** [comment]
I get a lot of errors due to references __ubsan_handle_type_mismatch. Would it be simpler just to set my laptop up to dual boot so I can do the model in linux on the laptop?

**Comment by richelbilderbeek** [comment]
Installing GNU/Linux is IMHO a good idea. It made me a better programmer for sure!

But doing a `Clean all` and commenting out UBSAN will work. And I *have* Travis set up to run your code with UBSAN.

So I think both options are fine. Sure I prefer the GNU/Linux install, but I do have a moral bias for FLOSS.

**Comment by JamesAndrews91** [comment]
Trying to stick to using Windows as I'm unsure if I am allowed to dualboot the laptop since it's owned by TRES, not me.

Now it's complaining it can't find the lboost_unit_test_framework. I tried adding it to the PATH and replacing:

LIBS += -lboost_unit_test_framework

with:

LIBS += C:/boost_1_63_0/stage/lib

but none of those options resolved the issue.

**Comment by richelbilderbeek** [comment]
There is a `.pro` file from @CarmenIJsebaart [at her MazeGame repo](https://github.com/CarmenIJsebaart/MazeGame/blob/master/MazeGame.pro) that may be of help.

I am sorry to say that I am sure your setup will not work: it should more likely be the combination of the two (using path and filename):

```
LIBS += C:/boost_1_63_0/stage/lib/libboost_unit_test_framework-mgw49-mt-d-1_59.a
```

Look up that folder and find the best fitting filename. I hope this helps.

Dual boot on TRES laptops sounds like a good idea: it will make you more productive. But not everybody loves GNU/Linux yet. You will have my support though :+1:

**Comment by JamesAndrews91** [comment]
Set the laptop to dual boot and it runs.
