### ISSUE TITLE
Peregrine Problems Part 2

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#227]
One of the missing .csv files for the article run of the pbd model gave the following .log file on peregrine:

![screenshot - 02012017 - 05 14 46 pm](https://cloud.githubusercontent.com/assets/22076213/22515399/a00a0d8e-e8a2-11e6-92ad-e86d4db027d5.png)

There are also some other curious .log files that gave " normal" .csv files but say they are running or they failed:

![screenshot - 02012017 - 05 08 43 pm](https://cloud.githubusercontent.com/assets/22076213/22515465/d7eb8354-e8a2-11e6-9313-50c0d5c3299d.png)
![screenshot - 02012017 - 05 10 28 pm](https://cloud.githubusercontent.com/assets/22076213/22515466/d7f013b0-e8a2-11e6-9731-ea178f42acd3.png)

Can we find the reason, logic and possible solution for these missing files and the other strange .log files in these files? @richelbilderbeek

**Comment by richelbilderbeek** [comment]
May it be rational to assume the files with status `RUNNING` are still running? Then it would follow that the `CSV`s are misattributed to them.

Note that the log file does not name the PBD output filename, I will fix that.

**Comment by JorikdeBoer** [comment]
What was the command to copy all files of a certain type (.csv or .log) to your own computer from peregrine?

**Comment by Lumphie** [comment]
scp studentnumber@peregrine.hpc.rug.nl:/home/studentnumber/folder/*.csv ~/folder/folder

**Comment by richelbilderbeek** [comment]
See github.com/richelbilderbeek/Peregrine

Look for `scp` (Secure Copy)

**Comment by Lumphie** [comment]
en als dat niet werkt nog een -r achter scp. In github.com/lumphie/research_phylogenies staat een copy folders from peregring script.

**Comment by richelbilderbeek** [comment]
Correct. `-r` (`recursive`) is a flag to also copy folders.

**Comment by JorikdeBoer** [comment]
is it possible that log files still say " running"  because the maximum walltime wasn' t long enough or was it caused by problems of peregrine itself? Because there are no running jobs left.

**Comment by richelbilderbeek** [comment]
No, it would give a more descriptive error, like 'exceeded time limit'.

Consider just running those jobs again.

**Comment by Lumphie** [comment]
Dear peregrine users,

At 4.00 am one of the metadata servers crashed.
We've restarted the metadata server and peregrine is usable again.

Regards,

Robin Teeninga 

Maybe this explains it

**Comment by JorikdeBoer** [comment]
What does this error from a .log file mean? 
![screenshot - 02022017 - 10 40 00 am](https://cloud.githubusercontent.com/assets/22076213/22544214/230e2846-e934-11e6-87db-2a3a330eb525.png)

these are the only clues: 
Error: unexpected ')' in ")"
Execution halted
Error: command failed

**Comment by richelbilderbeek** [comment]
I think there is a problem processing either a `.csv`/`.r` or any other text file.

As we have the parameters, I could try to fix it for you. I'll take a look.

**Comment by JorikdeBoer** [comment]
Here is an example: 

slurmstepd: error: Unable to create TMPDIR [/local/10789380]: Permission denied
slurmstepd: error: Setting TMPDIR to /tmp
Parameters loaded: birth_good: 0.5
birth_incipient: 0.3
completion: 0.3
death_good: 0.1
death_incipient: 0.1
time: 15
seed: 20
nltt_filename: jobo_pbd_nltt.csv
Error: unexpected ')' in ")"
Execution halted
Error: command failed

**Comment by richelbilderbeek** [comment]
I'll fix #232 first, as it appears simpler. Unless you disagree: you know your priorities better than I do.

**Comment by richelbilderbeek** [comment]
![issue](https://cloud.githubusercontent.com/assets/2098230/22551259/5ed3744c-e954-11e6-8d16-96dfbc71af48.png)

**Comment by richelbilderbeek** [comment]
In the GUI it runs fine:

![ok](https://cloud.githubusercontent.com/assets/2098230/22551575/9071284a-e955-11e6-8d4b-8746456dcfb8.png)

**Comment by richelbilderbeek** [comment]
Trying to reproduce the bug locally with:

```
./pbd 0.5 0.3 0.3 0.1 0.1 15 20 jobo_pbd_nltt.csv
```

**Comment by richelbilderbeek** [comment]
Works great:

```
p230198@pc-157-99:~/GitHubs/build-pbd-Desktop-Debug$ ./pbd 0.5 0.3 0.3 0.1 0.1 15 20 jobo_pbd_nltt.csv
Parameters loaded: birth_good: 0.5
birth_incipient: 0.3
completion: 0.3
death_good: 0.1
death_incipient: 0.1
time: 15
seed: 20
nltt_filename: jobo_pbd_nltt.csv
p230198@pc-157-99:~/GitHubs/build-pbd-Desktop-Debug$ 
```

**Comment by richelbilderbeek** [comment]
Hypothesis: `daic::set_r_working_directory` must be called.

Experiment: add those `assert`s, assuming files really exists.

**Comment by richelbilderbeek** [comment]
Final report has been handed in.
