### ISSUE TITLE
Get kewe.pro to compile

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#23]
`kewe.pro` does not compile, so I have patched two lines of `.travis.yml` to:

```
  #- qmake kewe.pro
  #- make
```

I suggest that @Lumphie gets `kewe.pro` to compile again and then uncomment the lines in the `.travis.yml` file.

**Comment by richelbilderbeek** [comment]
A friendly reminder to @Lumphie to fix this.
Probably need to modify the `kewe.pro` file a bit to fix this.

**Comment by Lumphie** [comment]
Done
