### ISSUE TITLE
elly: fix error

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#230]
The project of @EllyJet has ended. If that wasn't bad enough, the `elly` branch is left in a failing state. 

I'll have to make that branch work again.

**Comment by richelbilderbeek** [comment]
It appears that

 * a test has been written to introduce the new/correct/desired behavior
 * to get the test to run, it broke other tests. These were very basic tests.

I will unroll until only the newest test fails again, then add `FIX_ISSUE_` around it.

**Comment by richelbilderbeek** [comment]
It appears the culprit is `correct_branching_times`: it reverses the branching times.

Albeit that may be needed, I think it is located to high up in the code hierarchy. I think it maybe should only used for creating the DAISIE input file.

**Comment by richelbilderbeek** [comment]
I will document better what those branching times really mean.

**Comment by richelbilderbeek** [comment]
Hmmm, is `4` really a constant? I'd guess it should be replaced with `crown_age` instead.

```
std::vector<double> daic::correct_branching_times(const std::vector<double> brts)
{
  std::vector<double> corrected_brts(brts.size());
  for(int i = 0; i < static_cast<int>(brts.size()); ++i)
    {
      corrected_brts[i] = 4 - brts[i];
    }
  return corrected_brts;
}
```

**Comment by richelbilderbeek** [comment]
The constructor of `daic::input_row` is rather high up:

```
daic::input_row::input_row(
  const std::string& clade_name,
  const daic::species_status status,
  const int n_missing_species,
  const std::vector<double>& branching_times
):
  m_clade_name{clade_name},
  m_status{status},
  m_n_missing_species{n_missing_species},
  m_branching_times{correct_branching_times(branching_times)}
{
  if(m_branching_times.empty())
    throw std::invalid_argument("branching times cannot be empty");
}
```

**Comment by richelbilderbeek** [comment]
Removed `correct_branching_times`, because:

 * First get the tests to work again
 * It should be called `convert_branching_times`, as it converts the time unit from ?`mya` to ?`million years since the present` or ?`million years since crown age` or another way around
 * It has the `4` hardcoded, which must be replaced by a function argument unknown to me now

**Comment by richelbilderbeek** [comment]
The last test @EllyJet put in is documented and marked with `FIX_ISSEUE_230`. I hope to read in her report what should be added.

**Comment by EllyJet** [comment]
I forgot I left it so messy, sorry for that. If it is too much trouble maybe use the latest version that works?
What I was trying to fix was the way branching times were handles. when an event takes places after 1 mya, the branching time should be 3 mya ago. so 1 minus crownage, in that case 4.
The tests in this case should have been changed.

**Comment by richelbilderbeek** [comment]
> I forgot I left it so messy, sorry for that. 
No problemo.

> If it is too much trouble maybe use the latest version that works?
That's what I was doing :-)

> What I was trying to fix was the way branching times were handles. when an event takes places after 1 mya, the branching time should be 3 mya ago. so 1 minus crownage, in that case 4.
> The tests in this case should have been changed.
Yes, DAISIE uses other time units that we did. Next to this, the test marked `FIX_ISSUE_230` does disclose a bug. 

Perhaps one day someone continues or can use this work...
