### ISSUE TITLE
No linux in the canteen

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#231]
All the computers in the canteen give the waiting message for linux and don't work if I choose ignore......

**Comment by JorikdeBoer** [comment]
Did you have foreknowledge and is this the reason you work from home? @richelbilderbeek

**Comment by richelbilderbeek** [comment]
That's terrible! 

I sent an email to CIT, with you as BCC, so you can inform them in more detail. I hope you do. 

... but hey, you need a computer for that :confused:

**Comment by richelbilderbeek** [comment]
Ah, you may use that other operating system, Windows. It's closed-source, yet windely used. If you know Xubuntu, it should be easy to adapt to it. Just don't expect a useful terminal.

**Comment by richelbilderbeek** [comment]
> Did you have foreknowledge and is this the reason you work from home? @richelbilderbeek

Perhaps this is how a crying computer looks like :sunglasses:

**Comment by JorikdeBoer** [comment]
Linux seems to work again!

**Comment by JorikdeBoer** [comment]
just at the moment I found a terminal in windows...
