### ISSUE TITLE
pbd: filename in the log file

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#232]
If the complete pbd filename of the .csv could be printed in the log file, that would be great.
At the moment all the log-files give the same filename:
 nltt_filename: jobo_pbd_nltt.csv
Is it possible to turn this into:
nltt_filename: pbd_run_article_2_4_1_8.csv
@richelbilderbeek ?

**Comment by richelbilderbeek** [comment]
> If the complete pbd filename of the .csv could be printed in the log file, that would be great.

I'd bet a beer this already happen. I think the output *is* written to `jobo_pbd_nltt.csv`. 

UNDO: Ah, 'I'll check

**Comment by richelbilderbeek** [comment]
I see that `jobo` really needs five parameters. I guess I need to look at `pbd`...

**Comment by richelbilderbeek** [comment]
I see that `pbd` really needs eight parameters from the command-line...

**Comment by richelbilderbeek** [comment]
To quote myself then, now being sure about the bet:

> I'd bet a beer this already happens. I think the output *is* written to jobo_pbd_nltt.csv.

I think the problem is in the Peregrine job scripts.Which one do you use?

**Comment by JorikdeBoer** [comment]
The pbd_run_article job script

**Comment by JorikdeBoer** [comment]
in this case with new seeds so pbd_run_article_2

**Comment by richelbilderbeek** [comment]
Yuck, when removing the default parameter from pbd::parameters first, I get many compiler errors: I should one day seperate the biological parameters from the simulation overall parameters...

**Comment by richelbilderbeek** [comment]
I've found a bug and checked it in in `jobo`. I bet this fixed this problem. I will be adding it to the test suite (as I already should have...)
