### ISSUE TITLE
bdm: long simulations

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#233]
Note to self:
The simulations of 1000 generations, a population size of 10000 and a mutation rate of 0.01 (and sometimes a mutation rate of 0.1) take longer than 10 hours

**Comment by JorikdeBoer** [comment]
To-do list monday:
- Calculate the average nLTT plots of the i_2_3 nltt jobo jobscript
- Calculate the average nLTT plots for all 12 pbd parameters sets simulations
- Calculate the 6*12 nLTT statistics 
- Put all the missing graphs in the presentation
- Practice and improve the presentation

**Comment by Lumphie** [comment]
Can I see the practice? Can't make it to the real presentation. Have to go to the dentist at 15:20

**Comment by JorikdeBoer** [comment]
Depends how long it takes to fill all the empty slides....

**Comment by richelbilderbeek** [comment]
I'll happily be there as well. I do have a meeting with Rampal from 14:00-15:30

**Comment by JorikdeBoer** [comment]
the to-do list has been finished
