### ISSUE TITLE
Fill in research data management plan

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#24]
@Lumphie and @JorikdeBoer : please each fill in a RDMP and send it to @rsetienne before Thursday. I suggest to modify my personal one.

 * [x] @Lumphie: done!
 * [x] @JorikdeBoer : done!

This is the template:

[GELIFES-RDMP-template.docx](https://github.com/richelbilderbeek/pbdmms/files/575497/GELIFES-RDMP-template.docx)

This is my personal one:
[gelifes-rdmp-richel-bilderbeek.docx](https://github.com/richelbilderbeek/pbdmms/files/575498/gelifes-rdmp-richel-bilderbeek.docx)

**Comment by Lumphie** [comment]
Both done, that was quick!
