### ISSUE TITLE
Check what happened here

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#244]
How could this have been changed?

![issue](https://cloud.githubusercontent.com/assets/2098230/23215950/790dceb4-f914-11e6-9993-ec23aafd494e.png)

@Lumphie was a bit too enthousiastic I guess :smile: . 

Sure I'll fix it :muscle: , I just hope there is not much more...

**Comment by Lumphie** [comment]
huh wow. That's weird.

**Comment by richelbilderbeek** [comment]
Weird but fixed :-)
