### ISSUE TITLE
Jaan travis failure

### ISSUE THREAD

**Issue by JamesAndrews91** [richelbilderbeek/pbdmms#247]
Hi Richel,

I don't understand how to fix the error travis is giving me with my branch:

The command "if [[ $TRAVIS_BRANCH == "jaan" ]]; then make release; fi" exited with 2.

0.00s$ if [[ $TRAVIS_BRANCH == "jaan" ]]; then time ./jaan_EDSS; fi

/home/travis/build.sh: line 62: ./jaan_EDSS: No such file or directory

real	0m0.001s

user	0m0.000s

sys	0m0.000s

The command "if [[ $TRAVIS_BRANCH == "jaan" ]]; then time ./jaan_EDSS; fi" exited with 127.

0.01s$ if [[ $TRAVIS_BRANCH == "jaan" ]]; then gprof jaan_EDSS > gprof.log; fi

jaan_EDSS: No such file or directory

The command "if [[ $TRAVIS_BRANCH == "jaan" ]]; then gprof jaan_EDSS > gprof.log; fi" exited with 1.

0.00s$ if [[ $TRAVIS_BRANCH == "jaan" ]]; then head gprof.log -n 1000; fi

How do I correct this? It looks like it can't find the files but I don't know why?

Thank you

**Comment by richelbilderbeek** [comment]
I'll take a look now.

**Comment by richelbilderbeek** [comment]
Found the problem:

![issue](https://cloud.githubusercontent.com/assets/2098230/23405856/762e6a6c-fdbc-11e6-8a9a-0a7513776939.png)

**Comment by richelbilderbeek** [comment]
In the `jaan_EDSS.pro` file, I let `g++-5` be used instead of `g++`. 

Using `g++-5` *is* a workaround, thanks to CIT managing our access rights at the university. 

On the Peregrine cluster, you *should* use `g++`

**Comment by richelbilderbeek** [comment]
Just do a `git pull` :-)
