### ISSUE TITLE
fatal_error in newick

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#248]
Hey @richelbilderbeek,

Is this supposed to happen?

```
Error in library(ape) : there is no package called ‘ape’
Execution halted
unknown location(0): fatal error in "sado_is_newick": child has exited; pid: 23617; uid: 32260050; exit value: 1
../pbdmms/sado_newick_test.cpp(14): last checkpoint
```

**Comment by Lumphie** [comment]
Maybe I don't have any R libraries on my local computer? I can't see if it works on Travis because I can't see the build logs.

**Comment by richelbilderbeek** [comment]
Try running

```
./install_r_packages
```

**Comment by richelbilderbeek** [comment]
Note to self: for getting this to work for students,

as localadmin (PhD, postdoc, someone with more rights) do on that computer:

```
sudo apt-get libcurl4-openssl-dev
```

as student:

```
rstudio
```

then select 'Tools -> Install packages` then install `devtools`

Now that script can run without problems.

Todo: document this.

**Comment by Lumphie** [comment]
Works for now.
