### ISSUE TITLE
sado: Get indivs in correct species

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#249]
I was thinking about using connected components and filtered graphs

**Comment by Lumphie** [comment]
Marked as `FIX_ISSUE_249`

**Comment by richelbilderbeek** [comment]
assert fails here:

```
void sado::add_edges_impl_2(
  const attractivenesses& as,
  genotype_graph& g,
  const double min_attractiveness
)
{
  assert(is_valid(as));
```

It is right: `attractivenesses` is a matrix that should have a diagonal of zeroes, as individuals have a zero probability to mate with themselves.

**Comment by Lumphie** [comment]
This seems to work. Only one thing I overlooked. The model is able to give output every X generations. So there won't be any parents in generation 0 for individuals in generation X if X does not equal 1.
Easily fixed by just giving output every generation, but no so easily fixed if we want to keep the flexible output.
