### ISSUE TITLE
lumphie: give presentation

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#256]
I added a rough sketch of the presentation. Needs pictures and other content. 
Most text is not final.

Take a look if you want, it can be found in the folder documentation.

**Comment by Lumphie** [comment]
@richelbilderbeek, If I actually have results before thursday I'd like to practice the presentation for you on monday, is that okay?

**Comment by Lumphie** [comment]
Presentation will be moved 2/3/7 weeks

**Comment by Lumphie** [comment]
@richelbilderbeek What do you think? Tried to do what Rampal told me to.

[Sympatric Speciation.pdf](https://github.com/richelbilderbeek/pbdmms/files/893916/Sympatric.Speciation.pdf)

**Comment by richelbilderbeek** [comment]
Nice. Some feedback:

 * Consider an explicit research question as early as possible, as it shapes the way the audience thinks
 * Consider adding a reference to the article you got the model from, unless Van Doorn only made one famous theoretical model
 * Consider replacing the parameters symbols by a more general story: what does the model do, in English?
 * I enjoy the dot in slide 9. It shows that a parameter combination you chose is rational. Consider showing also the other the parameters combinations you picked, also in slide 10

Working on more feedback...

**Comment by richelbilderbeek** [comment]
More feedback:

 * Consider adding an explicit research question
 * Put in [your latest result](https://github.com/richelbilderbeek/pbdmms/issues/261#issuecomment-291562059) and tell why you did not find it sooner
 * In 'Future Research', consider removing  'Check code', unless there is good reason not to trust a published result
 * In 'Future Research', 'Keep trying other parameters' can -thanks to the last result- be rephrased/removed now
 * In 'Future Research', 'Map female preference – male trait' and 'Better map of female preference' may sound a bit repetitive 
 * In 'Future Research', you recommend the 'Number of generations' to -I guess- increase. I hope you see a better reason then 'something *may* happen then'

I think that is feedback aplenty. Good luck!

**Comment by Lumphie** [comment]
Thanks for the feedback! Working on it now

**Comment by Lumphie** [comment]
* Consider an explicit research question as early as possible, as it shapes the way the audience thinks

Done

 * Consider adding a reference to the article you got the model from, unless Van Doorn only made one famous theoretical model

Done


 * Consider replacing the parameters symbols by a more general story: what does the model do, in English?

The real presentation has animations and will be more of a story, thanks for mentioning it.

 * I enjoy the dot in slide 9. It shows that a parameter combination you chose is rational. Consider showing also the other the parameters combinations you picked, also in slide 10

Added an arrow (slide 9) and an area (slide 10)

 * Consider adding an explicit research question

Done

See first feedback

 * Put in [your latest result](https://github.com/richelbilderbeek/pbdmms/issues/261#issuecomment-291562059) and tell why you did not find it sooner

Added

 * In 'Future Research', consider removing  'Check code', unless there is good reason not to trust a published result

Done

 * In 'Future Research', 'Keep trying other parameters' can -thanks to the last result- be rephrased/removed now

Removed


 * In 'Future Research', 'Map female preference – male trait' and 'Better map of female preference' may sound a bit repetitive 

1st is correlation, second is spectrum. Will rephrase

 * In 'Future Research', you recommend the 'Number of generations' to -I guess- increase. I hope you see a better reason then 'something *may* happen then'

Has 2 reasons:

1. I hope to increase the spectrum of female preference so that specificity for mate type is more specialized than the spectrum.

2. New result are paper parameters, but not with just 1000 individuals. 4000-5000 individuals instead.

Thanks again! Really useful

**Comment by richelbilderbeek** [comment]
Great, I look forward to it!

**Comment by Lumphie** [comment]
[Sympatric Speciation.pdf](https://github.com/richelbilderbeek/pbdmms/files/894549/Sympatric.Speciation.pdf)

I'm dropping this here, just in case.

**Comment by richelbilderbeek** [comment]
Better! Well done!

**Comment by richelbilderbeek** [comment]
Presentation has been given, so this Issue can be closed.
