### ISSUE TITLE
sado: test simulations for maximum likelihood

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#258]

**Comment by Lumphie** [comment]
```
"","b","mu_1","lambda_1","mu_2","loglik","df","conv"
"1",9.55075294948038e-16,0.501896046680655,0.255269574604608,0.501896046680655,0,3,0

```

**Comment by Lumphie** [comment]
That's for 50 generations 1 species every generation.

**Comment by Lumphie** [comment]
![tree_reconstructed](https://cloud.githubusercontent.com/assets/21882358/23945245/1f7a920c-0976-11e7-9740-5bd519340827.png)

**Comment by Lumphie** [comment]
![eco_traits](https://cloud.githubusercontent.com/assets/21882358/23945550/32cddd72-0977-11e7-8dfc-69d1bd170aed.png)

This looks weird though

**Comment by Lumphie** [comment]
```
histbin 0.1 0.1 0.1 0.1
seed 123
pop0 100
type0 0 0 0
end 50
sc 0.1
se 0.05
sk 1.2
c 0.05
sm 0.2
sv 0.03
sq 1.0
eta 1.0
b 4.0
output 1 output.txt
erasure_method swap
initialization_bug 0
gausser_implementation lut
at 0.05

```

```
reconstucted tree:

maximum likelihood analysis:
NA
ICE default IO error handler doing an exit(), pid = 5961, errno = 32
```

Something went wrong. The full_tree.png is empty (so reconstructed tree is also empty)

**Comment by Lumphie** [comment]
![eco_traits](https://cloud.githubusercontent.com/assets/21882358/23948649/3da121fc-0984-11e7-9ccd-8992a00cc8e3.png)

There is a weird bug. This is supposed to be 1 generation

**Comment by Lumphie** [comment]
@richelbilderbeek 

SPECIATION!

```
reconstucted tree:
(:2,:2):48;

maximum likelihood analysis:
b: 0.0243252
mu_1: 11.8106
lambda_1: 2.66741e-07
mu_2: 11.8106
loglik: -9.33209e-11
df: 3
conv: 0
```

**Comment by richelbilderbeek** [comment]
> Something went wrong. The full_tree.png is empty (so reconstructed tree is also empty)

Maybe the population went extinct? Then it is a feature. Would it be something else, there is need for a new test :muscle:

**Comment by Lumphie** [comment]
Don't know. I don't think they went extinct.
