### ISSUE TITLE
sado: not all individuals in species have a unique ID

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#260]
This is a potential bug. I am on it now.

**Comment by Lumphie** [comment]
Because individuals can live in multiple generations they will definitely be in multiple species. Then later the species get merged and the same individual ends up in the same species a number of times.

**Comment by richelbilderbeek** [comment]
Bug is -ironically- in `create_init_with_bug`. Fixed now.

**Comment by richelbilderbeek** [comment]
'Naive' fix breaks the Golden Standard:

```
sado::population sado::create_initial_population(const parameters &p)
{
  // Unique species ID, but breaks Golden Standard
  //  std::vector<indiv> v;
  //  v.reserve(p.get_pop_size());
  //  std::generate_n(
  //    std::back_inserter(v),
  //    p.get_pop_size(),
  //    [p]() { return create_init_with_bug(p.get_x0(), p.get_p0(), p.get_q0(), p); }
  //  );
  //  return population(v);

  // Creates individuals with same species ID
  //return population(
  //  std::vector<indiv>(
  //    p.get_pop_size(),
  //    create_init_with_bug(p.get_x0(), p.get_p0(), p.get_q0(), p)
  //  )
  //);
  
}
```

**Comment by richelbilderbeek** [comment]
> Because individuals can live in multiple generations they will definitely be in multiple species.

Thanks for the suggestion, but this has nothing to do with the problem. Each individual should have a unique ID.

It is tempting to make this another initialization bug...

**Comment by richelbilderbeek** [comment]
> It suggests the Golden Standard creates all individuals with the same random values of p, q and x. Not too much variation caused by this noise if you ask me.

Uh, I *was* right. Here a snippet from the original code:

```
void initialize(void)
{
    bigint j;
    int k;
    indiv I;

    SetSeed(seed);
    I.init(x0,p0,q0);

    for(j=0;j<popsize;j++)
        pop.push_back(I);

  // ...
}
```

I will remain backwards compatible. :persevere:

**Comment by richelbilderbeek** [comment]
Well, it has been done: all individuals in the first generation are unique :rainbow:
