### ISSUE TITLE
Run sado

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#261]
@richelbilderbeek 

Could you run sado with the following parameters?

```
alleles 1 1 1 
histbin 0.1 0.1 0.1 0.1
seed 314
pop0 100
type0 0 0 0
end 800
sc 0.6
se 0.5
sk 1.2
c 0.01
sm 0.1
sv 0.02
sq 1.0
eta 1.0
b 4.0
output 1 output.txt
erasure_method swap
initialization_bug 0
gausser_implementation lut
diploid 1
at 0.05
```

If there are little to no individuals per generations then scale down c and when there are too many scale it up.

**Comment by Lumphie** [comment]
Changed output to 1. Otherwise it will never find the parents.

**Comment by richelbilderbeek** [comment]
Sure, I am running now:

```
alleles 1 1 1 
histbin 0.1 0.1 0.1 0.1
seed 314
pop0 100
type0 0 0 0
end 800
sc 0.6
se 0.5
sk 1.2
c 0.01
sm 0.1
sv 0.02
sq 1.0
eta 1.0
b 4.0
output 1 output.txt
erasure_method swap
initialization_bug 0
gausser_implementation lut
diploid 1
at 0.05
```

**Comment by Lumphie** [comment]
Getting an error:

```
Segmentation fault (core dumped)
convert_dot_to_svg: warning: command 'dot -Tsvg save_to_png.dot -o save_to_png.svg' resulting in error 35584convert_dot_to_svg: failed to create SVG output file 'save_to_png.svg'
ICE default IO error handler doing an exit(), pid = 18628, errno = 32
```

**Comment by richelbilderbeek** [comment]
Hmmm, that simulation does still take some time, I will use that time to (try to improve) the speed on the `sado_profile` branch.

**Comment by richelbilderbeek** [comment]
For the error, I've created #262 . Perhaps there is the solution.

**Comment by richelbilderbeek** [comment]
Simulation took too long. I interrupted it and started working on #251 again.

**Comment by Lumphie** [comment]
Note to self: 

Using rm -rf to remove the folder sado is currently working in is not the best idea ever!

**Comment by Lumphie** [comment]
I don't know where it left the newick, but I found it it then "calc_max_likelihood.R"

"(:12,:12):988;" Is the first newick!

**Comment by Lumphie** [comment]
For a good time type `sl` instead of `ls`

**Comment by Lumphie** [comment]
![increasing_generations](https://cloud.githubusercontent.com/assets/21882358/24452880/be9cae5a-1485-11e7-8328-d03ca3acfe50.gif)

**Comment by Lumphie** [comment]
@richelbilderbeek Of course the evening before the presentation I find this...

histbin 0.1 0.1 0.1 0.1
pop0 1000
type0 0 0 0
sc 0.4
se 0.6
sk 1.2
sv 0.02
eta 1
b 4.0
output 1 output.txt
erasure_method swap
initialization_bug 0
gausser_implementation lut
at 0.05
c 0.0005
end 900
sm 0.2
sq 1.0
seed 1

![male_traits](https://cloud.githubusercontent.com/assets/21882358/24668501/679a832a-1967-11e7-88b0-55decf9f36af.png)

These are the male traits of the above parameters.

I wonder what would happen when the simulation runs longer than 900 generations.

**Comment by richelbilderbeek** [comment]
Great! That rejects one hypothesis!

**Comment by richelbilderbeek** [comment]
Done.
