### ISSUE TITLE
pbdmms does not build anymore on Travis CI

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#263]
Posted bug report at [the igraph GitHub](https://github.com/igraph/igraph/issues/979).

**Comment by Lumphie** [comment]
It does build fine right now?

**Comment by richelbilderbeek** [comment]
My fault: I've renamed the Issue: it does not build on Travis CI.

**Comment by richelbilderbeek** [comment]
Fixed it! Cause was that the redirection of `g++` to `g++-5` must be done *after* the installation of R packages
