### ISSUE TITLE
sado: Error: Newick Empty

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#265]
4000 generations takes long so decided to test with just 10.
The newick resulted in NA.
Is it a feature?

```
histbin 0.1 0.1 0.1 0.1
seed 123
pop0 1000
type0 0 0 0
end 10
sc 0.7
se 0.5
sk 2.4
c 0.002
sm 0.1
sv 0.03
sq 1.0
eta 1.0
b 4.0
output 1 output.txt
erasure_method swap
initialization_bug 0
gausser_implementation lut
at 0.05
```

**Comment by Lumphie** [comment]
They are not extinct

```
0 1000 -1 1 -1
-0.0234087 -0.0103018 0.0174802 2.74223e-16 2.16949e-16 1.66617e-16
1 500 1 1 1
-0.0234087 -0.0103018 0.0174802 5.55667e-17 5.38303e-17 6.25126e-17
2 388 0.107869 0.309185 0.18583
-0.0149972 -0.00144839 0.0343424 0.0245155 0.0249014 0.0294465
3 373 0.0193858 0.0337055 0.0649936
-0.0096492 0.00789665 0.046097 0.0356341 0.0344758 0.0417153
4 349 0.00823656 0.0340386 0.0535798
-0.00741551 0.00908943 0.0450476 0.0455304 0.0430544 0.0487853
5 401 0.0303541 -0.0154891 0.125902
-0.00421442 0.010204 0.0436553 0.0489415 0.0544619 0.0569997
6 372 0.000741638 -0.0464734 0.136001
-0.00425277 0.0201754 0.0400592 0.052887 0.0616932 0.0642486
7 375 0.0547303 -0.0349249 -0.00925125
-0.00221331 0.0200325 0.0340121 0.0544977 0.0659089 0.0666946
8 362 -0.00863049 -0.00468531 0.0123087
-0.0012264 0.0146066 0.0297552 0.0626514 0.0703907 0.0712144
9 390 -0.00231607 -0.0261588 0.0285672
-0.00522006 0.00986273 0.0306067 0.0691223 0.0709758 0.0713857
10 362 0.0094611 -0.0659847 0.11571
-0.00340526 0.0136023 0.0261932 0.0719778 0.0793292 0.0718562
reconstucted tree:

maximum likelihood analysis:
NA
```

**Comment by Lumphie** [comment]
100 generations also has maximum likelihood analysis: NA

**Comment by Lumphie** [comment]
@richelbilderbeek

**Comment by richelbilderbeek** [comment]
This is a feature to do ML when the Newick is empty.

Question is: why is the Newick empty.

**Comment by richelbilderbeek** [comment]
I am working on #266 and #264 so I hope you write a test to reproduce this error/problem/feature and find out which of these three options it is.

**Comment by Lumphie** [comment]
I will!

**Comment by richelbilderbeek** [comment]
Convenient for GUI (just added this feature):

[issue_265.txt](https://github.com/richelbilderbeek/pbdmms/files/861373/issue_265.txt)

**Comment by Lumphie** [comment]
![error_newick](https://cloud.githubusercontent.com/assets/21882358/24201846/9636870c-0f11-11e7-9893-9a3ed167ab49.png)

Hmmm, @richelbilderbeek

**Comment by Lumphie** [comment]
![eco_traits](https://cloud.githubusercontent.com/assets/21882358/24201881/b6787fd4-0f11-11e7-9e1b-55c2df0eb509.png)

It's the end of this tree

**Comment by Lumphie** [comment]
![tree_reconstructed](https://cloud.githubusercontent.com/assets/21882358/24202058/389ca8c8-0f12-11e7-899d-6f65b0907172.png)

Something is going wrong with reconstructing

**Comment by Lumphie** [comment]
That last one used the same parameters, but just 10 generations.

**Comment by Lumphie** [comment]
![tree_full](https://cloud.githubusercontent.com/assets/21882358/24202203/b05fd560-0f12-11e7-913f-6ab74dc40ab2.png)
![tree_reconstructed](https://cloud.githubusercontent.com/assets/21882358/24202202/af78b81a-0f12-11e7-9c96-89e561291472.png)

**Comment by richelbilderbeek** [comment]
Hey, that's great! It will help me catch the problem.

**Comment by Lumphie** [comment]
Writing tests as we speak.

**Comment by richelbilderbeek** [comment]
Ha, same here :-)

**Comment by Lumphie** [comment]
Testing if 4 species that go in the same species is a problem. Shouldn't be.

/*
                           time

     [5]            [5]      + present, generation 2
      |              |       |
      |              |       |
     [4]___    ->   [4]      + past, generation 1
    / | \  \__       |       |
   /  |  \    \      |       |
  [0] [1] [2] [3]   [0]      + past, generation 0

  */

**Comment by Lumphie** [comment]
It is indeed not a problem.

**Comment by Lumphie** [comment]
```
/*
                           time

      [5]            [5]      + present, generation 2
     / | \            |       |
    /  |  \           |       |
   |   |  [4]   ->   [4]      + past, generation 1
   |   |   |\         |       |
   |   |   | \        |       |
  [0] [1] [2][3]     [0]      + past, generation 0

  */
```

also not a problem

**Comment by Lumphie** [comment]
/*
                                 time

      [6] [7]           [6]      + present, generation 3
       |   |             |       |
       |   |             |       |
      [4] [5]_          [4]      + past, generation 2
     / |\\_|_ \          |       |
    /  | \ | \ |    ->   |       |
   |   |  [2] [3]       [?]      + past, generation 1
   |   |                 |       |
   |   |                 |       |
  [0] [1]               [0]      + past, generation 0

  */

**Comment by richelbilderbeek** [comment]
The problem appears to be that [2] and [3] do not have an ancestor from generation 0...

**Comment by Lumphie** [comment]
It's added in commit: `6b73827 `

**Comment by richelbilderbeek** [comment]
Great, I am very close to having found the reason why it freezes...

**Comment by richelbilderbeek** [comment]
Found reason ( #264 ), will now look at the failing test.

**Comment by richelbilderbeek** [comment]
Marked with `FIX_ISSUE_265`

**Comment by richelbilderbeek** [comment]
Hey, it works:

![fixed](https://cloud.githubusercontent.com/assets/2098230/24348015/868318da-12da-11e7-9aa8-1fc801d39a24.png)
