### ISSUE TITLE
Pbd control group

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#271]
I'm not sure, but I think I need a control group from different kinds of pbd trees. Just to get the error marge of the maximum likelihood and to be able to compare the sado to anything. Is that right?

**Comment by richelbilderbeek** [comment]
It is important to know the uncertainty/error of measurements.

One trick already suggested is to generates trees from the ML estimates, but from #270 this may be impossible, but this may help:

> pbd_bootstrap {PBD}
>
> Bootstrap analysis under protracted birth-death model of diversification
> 
> Description
> 
> Likelihood maximization for protracted birth-death model of diversification followed by simulations of the model using the maximum likelihood parameter estimates to compute an estimate of the error in these estimates and to assess the goodness-of-fit of the model by comparing maximum likelihoods of the simulated data sets to the maximum likelihood of the real data set.

I will take a look at it today to gauge its use.

**Comment by richelbilderbeek** [comment]
I have taken a look at this and am now implemeting it at #273

**Comment by richelbilderbeek** [comment]
Boostrap demo here:

[PBD_ML_demo.pdf](https://github.com/richelbilderbeek/pbdmms/files/878513/PBD_ML_demo.pdf)

**Comment by richelbilderbeek** [comment]
It has been done.
