### ISSUE TITLE
sado: infinite loop

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#274]
The simulation is supposed to end if the species go extinct. This does not happen when there is just 1 indiv left. Even though there is no other individual left to mate with it will keep looking for that significant other in an infinite loop.

Maybe change the while loop so that it also stops when there is just 1 indiv left.

**Comment by richelbilderbeek** [comment]
Fun! I am nearly done, so within two hours I may have added that. Assign me if you'd like me to :-)

**Comment by richelbilderbeek** [comment]
Maybe fixed!
