### ISSUE TITLE
No green light

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#28]
@richelbilderbeek 

Readme does not give me green light even though Travis says otherwise!

https://travis-ci.org/richelbilderbeek/pbdmms/builds/174188913

**Comment by richelbilderbeek** [comment]
What is the problem? Everything looks fine on my screen:

![okidokie](https://cloud.githubusercontent.com/assets/2098230/20099725/5fbdd196-a5ba-11e6-89fa-6b2c93e00352.png)

**Comment by Lumphie** [comment]
Okay weird, now it works :\
