### ISSUE TITLE
Add OCLint on kewe

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#29]
At this moment, all files with `kewe_` are ignored by OCLint.

In `do_oclint.sh`, replace this:

```
cpp_files=`ls *.cpp | egrep -v "^qrc_.*\.cpp$" | egrep -v "^moc_.*\.cpp$" | egrep -v "^.*_test\.cpp$" | egrep -v "^kewe_.*\.cpp$"`
h_files=`ls *.h | egrep -v "^ui_.*\.h$" | egrep -v "^kewe_.*\.h$"`
```

by 

```
cpp_files=`ls *.cpp | egrep -v "^qrc_.*\.cpp$" | egrep -v "^moc_.*\.cpp$" | egrep -v "^.*_test\.cpp$"`
h_files=`ls *.h | egrep -v "^ui_.*\.h$"`
```

@Lumphie : want to try first yourself and on your own branch?

**Comment by Lumphie** [comment]
Damnit, I hoped you wouldn't find out :(

**Comment by Lumphie** [comment]
Oh it is already replaced in my branch?

**Comment by richelbilderbeek** [comment]
Could be, now I am doubting...

**Comment by richelbilderbeek** [comment]
It *has* already been replaces. Blimey, I am too pro-active :sunglasses:
