### ISSUE TITLE
Fix Codecov ignoring kewe

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#37]

**Comment by richelbilderbeek** [comment]
Busy fixing it...

**Comment by richelbilderbeek** [comment]
Loss of codecov seems to spread :confused:

**Comment by Lumphie** [comment]
kewe namespace is a codecov virus!

**Comment by richelbilderbeek** [comment]
I think is has to do with testing on own branches, my bash has never been great...

**Comment by richelbilderbeek** [comment]
Hypothesis confirmed, need to use `TRAVIS_BRANCH` in `.travis.yml`

**Comment by richelbilderbeek** [comment]
I appears to have fixed it, then live dangerously, as I already checked it in on `master` :stuck_out_tongue_winking_eye: :vulcan_salute:

**Comment by richelbilderbeek** [comment]
`master` and `ribi` are up again :sunglasses:

**Comment by richelbilderbeek** [comment]
This looks great, as if all that is need is patience:

![okidokie](https://cloud.githubusercontent.com/assets/2098230/20179920/8aadd2a8-a758-11e6-87b8-87079b118de0.png)

**Comment by richelbilderbeek** [comment]
First glimpse of `kewe` in Codecov:

![kewe](https://cloud.githubusercontent.com/assets/2098230/20180538/286b011c-a75b-11e6-8bc8-7c5656772b48.png)

**Comment by Lumphie** [comment]
Still no CodeCov :'-(

**Comment by richelbilderbeek** [comment]
Perhaps I'll contact Codecov....

**Comment by richelbilderbeek** [comment]
Contacted codecov.

**Comment by richelbilderbeek** [comment]
@Lumphie : I think this looks good:

![kewe_codecov](https://cloud.githubusercontent.com/assets/2098230/20264474/071e4c62-aa6c-11e6-8f0f-fd5dd9ef23d5.png)

I am working on getting codecov to work locally until Steve from Codecov helps us out.

**Comment by richelbilderbeek** [comment]
@Lumphie: 

This is how I got that figure:

```
cd pbdmms
./get_codecov_local_init.sh 
qmake kewe_test.pro; make debug; ./kewe_test
./get_codecov_local_after.sh  
```

It will start firefox showing the code coverage.

The scripts are in the `master` branch. Good luck merging :+1:

**Comment by richelbilderbeek** [comment]
@Lumphie : look [here](https://codecov.io/gh/richelbilderbeek/pbdmms/tree/4328257949a4e9985a8cfef0f4dacd91ec1da851) is some codecov!

I've found that URL at the bottom of a Travis Build log, with 'View Raw Log':

![hiero](https://cloud.githubusercontent.com/assets/2098230/20265720/f71954cc-aa72-11e6-8632-e0d645284b58.png)

**Comment by richelbilderbeek** [comment]
Steve fixed it!
