### ISSUE TITLE
kewe: add results curves in gui

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#43]
2 have been done, some more to go.

**Comment by richelbilderbeek** [comment]
I assumed you want to try yourself first? I think it will be easy for you :sunglasses:

**Comment by richelbilderbeek** [comment]
Ah, perhaps you assigned you

**Comment by richelbilderbeek** [comment]
Oops....

**Comment by Lumphie** [comment]
That's why I made a kewe issue 😎

**Comment by richelbilderbeek** [comment]
You make me proud :+1:

**Comment by richelbilderbeek** [comment]
Oops, pushed just a second ago!

**Comment by Lumphie** [comment]
@richelbilderbeek https://github.com/richelbilderbeek/pbdmms/blob/master/Screenshots/kewe_gui2.png

Added lines in graph (removed population size, because it is constant.
Histograms through time are no longer visible?

**Comment by richelbilderbeek** [comment]
Someone must have accidentally deleted the call to `plot_parameter_results` (or something like that).

**Comment by Lumphie** [comment]
Can't find it. 

It still says:

`ui->eco_trait->SetSurfaceGrey(r.m_ecological_trait);
  ui->male_sexual_trait->SetSurfaceGrey(r.m_male_trait);
  ui->female_preference->SetSurfaceGrey(r.m_female_preference);`

But doesn't make the graphs visible or something. I can't find it.

**Comment by richelbilderbeek** [comment]
Let's do this after lunch?

**Comment by richelbilderbeek** [comment]
I'd guess that the `results` class has empty `r.m_ecological_trait`, `r.m_male_trait` and `r.m_female_preference` :cocktail:

**Comment by Lumphie** [comment]
I'm at work after lunch. Let's do this monday!

**Comment by richelbilderbeek** [comment]
Sounds like a plan!

**Comment by Lumphie** [comment]
Fixed
