### ISSUE TITLE
Competition

### ISSUE THREAD

**Issue by LykeStuurman** [richelbilderbeek/pbdmms#46]
Al een code coverage van 80%! volgens mij moet Kees maandag de koffie gaan halen....gheghe
@richelbilderbeek 
@Lumphie 
@JorikdeBoer

**Comment by richelbilderbeek** [comment]
You suggest for #5 to use a rule `Kees should always fetch coffee`?

**Comment by LykeStuurman** [comment]
I suggest that the person with the lowest code coverage should always fetch coffee.

**Comment by richelbilderbeek** [comment]
At the moment, that is you... you acknowledge that?

**Comment by LykeStuurman** [comment]
Not anymore!!

**Comment by richelbilderbeek** [comment]
Well done. You consider a failing build and/or OCLint unimportant in this decision?

**Comment by LykeStuurman** [comment]
No, you are right, that is important. So who do you think should fetch coffee at the moment?

**Comment by richelbilderbeek** [comment]
It's hard to reach consensus on this, as 41 issues ago we started looking for it, see #5

**Comment by LykeStuurman** [comment]
too bad richel. I am nr 500! @richelbilderbeek

**Comment by richelbilderbeek** [comment]
I wanted to offer that people that push the 500th build should always bring coffee...

**Comment by richelbilderbeek** [comment]
There *is* a strong sentiment for letting people breaking the `master` fetching coffee...

![koffievoorrichel](https://cloud.githubusercontent.com/assets/2098230/20455043/abe77c80-ae51-11e6-8ba9-1c68d7338a0b.png)

**Comment by LykeStuurman** [comment]
well.. it is a good motivation to get it working again!

**Comment by richelbilderbeek** [comment]
We are sure you won't let the team down too often :sunglasses:

**Comment by richelbilderbeek** [comment]
I close this Issue as it is a duplicate of #5
