### ISSUE TITLE
Mechanism for being good

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#5]
Breaking the build is bad. Yet, it does happen.
Having a low code coverage is bad. Yet, it does happen.
Having a big OCLint report is bad. Yet, it does happen.

I suggest we devise a simple mechanism to keep each other doing the right thing. For example: The Bad Person has to fetch coffee/tea for the others. The Bad Person is the person with the highest BPS (Bad Person Score), which is calculated as such:

```
BPS = 200 * has_broken_the_build 
  + (100 - lowest code coverage file in his namespace) 
  + number of OCLint lines
```

Any suggestions?

**Comment by Lumphie** [comment]
Starting in 2 weeks?

**Comment by richelbilderbeek** [comment]
I suggest immunity when:

 * you are Kees and the date is before Tuesday 25th
 * you have a score lower than 10

**Comment by richelbilderbeek** [comment]
Punishment should be constrained to only when breaking the master build.

For this, first the full team needs to be able to work with branches.

**Comment by richelbilderbeek** [comment]
It appears the one breaking the master (often me) is the one getting coffee (often me)...

**Comment by richelbilderbeek** [comment]
I think this mechanism is already informally in place, thus closing this Issue.
