### ISSUE TITLE
Definition and use of incipient group/species

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#53]
I suggest the following definition of an incipient group: a group of genotypes that would be counted as good species  if one or more genotypes would be removed. 

To close the gap between the mechanistic models and the PBD-model we could look at the possibility
to look back at previous generation to see which of the individuals from an incipient group were in the past counted as part of a good species group (and don't  need to be counted as incipient in the present) and which individuals in the incipient group are new and could be called incipient according to the PBD-model. If you have your own defenition, please commit @richelbilderbeek ,@lumphie!

**Comment by richelbilderbeek** [comment]
Great point! I'll look into it ASAP.

Franjo suggested [1], as it would contain 'a clear-cut definition of what a good and an incipient species really is'. Anyone volunteers to look at that article (I guess @JorikdeBoer would be eager)? I have it on my desk.

## References

 * [1] Weissing, Franz J., Pim Edelaar, and G. Sander Van Doorn. "Adaptive speciation theory: a conceptual review." Behavioral ecology and sociobiology 65.3 (2011): 461-480.

**Comment by Lumphie** [comment]
I'd rather say that an incipient species is a potential good species hidden in another good species, because it makes way more sense with how the PBD model is set up.

But I don't mind what we'll settle on as long as we do settle on something.

**Comment by richelbilderbeek** [comment]
Time made this point obsolete.
