### ISSUE TITLE
Fix bug no interaction female pref - male trait

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#62]
Female preference and male trait seem to be totally unrelated.
P of -1 and Q of 1 can mate fine.

**Comment by Lumphie** [comment]
It looks like this happens because of a big number issue.

An attractiveness (or chance of mating) of 0.0001 might look like a little, but if it tries to mate 10.000 times it will happen once. And this model keeps trying until there are enough babies. So it might try more than 10.000 times (if every individual is very little attracted to every other individual)

**Comment by Lumphie** [comment]
It almost looks like they are shifting away from each other.

**Comment by richelbilderbeek** [comment]
Well observed! It *is* a thumbs-up if one can observe a bug :+1:

**Comment by Lumphie** [comment]
![kewepreftraitbug](https://cloud.githubusercontent.com/assets/21882358/20538389/4642acc2-b0f1-11e6-9f16-a29a32fc463d.png)

No, not a feature (I guess?)

**Comment by richelbilderbeek** [comment]
I assume you test the function to calculate attractiveness now :sunglasses:

**Comment by Lumphie** [comment]
` ///Check if they will mate
          double a = gauss(mother._p() - father._q(), parameters.sim_parameters.sm)
                   * gauss(mother._x() - father._x(), parameters.sim_parameters.se);

          if (Uniform() > a)`

Not a function because it's a "single" line.

**Comment by Lumphie** [comment]
It happens because individuals can't die and it will always result in a fixed population size.

Before the female could "decide" not to mate and live till the next generation (and either mate, not mate or die in that generation)

**Comment by richelbilderbeek** [comment]
Well, the calculation of that `a` ...

```
double a = gauss(mother._p() - father._q(), parameters.sim_parameters.sm)
* gauss(mother._x() - father._x(), parameters.sim_parameters.se);
```

could also be

```
const double a = calculate_p_mate(mother, father);
```

where that function `calculate_p_mate` is the chance the two individuals mate. That function can be tested.

**Comment by Lumphie** [comment]
That's true. Will write and will test.

**Comment by Lumphie** [comment]
Oh and I just noticed you added some suggestions that broke my build :\

**Comment by richelbilderbeek** [comment]
Yes, feel free to ignore/delete/temporarily disable them (I told the same to the others).

**Comment by richelbilderbeek** [comment]
Well done!

**Comment by Lumphie** [comment]
Argh

**Comment by richelbilderbeek** [comment]
So, `<` should have been `>`. Well spotted!

**Comment by Lumphie** [comment]
Yes, it works again. Now I'll have to find speciation and/or branching
