### ISSUE TITLE
Fix SES getting stuck

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#64]
There is probably no individual that is fit enough to mate.

**Comment by Lumphie** [comment]
Maybe the initial population needs to differ a bit so the chance of surviving gets a bit bigger.

**Comment by Lumphie** [comment]
Might be fixed with the other bug fixed (chance of mating was inverted)

**Comment by richelbilderbeek** [comment]
After having optionally followed the Beyonce principle ([from talk of Kris Jusiak](https://www.youtube.com/watch?v=T3uMcxhzRUE)), feel free to close this Issue.
