### ISSUE TITLE
Implement competition in SES

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#65]
Sander used a strength of viability selection on male mating type(sigma_s or sq (in the model)), basically giving the male traits a cost distribution. 

Right now there is no competition in my model, not for the ecological type and not for the male trait.

- [x] Decide (not) to implement competition
- [x] Decide to compete for eco type or eco type and male trait
- [x] Think of where to implement it (check if babies are fit enough, or kill of parents at the start at of a new generation)
- [x] Implement it

**Comment by Lumphie** [comment]
I will have to implement competition to get disruptive selection.

Not sure yet if I want the male trait to have a cost.

Thinking of not letting the parents mate if their fitness is too low, because it doesn't make sense that a very low fitness parent with a very high fitness parent can get a viable baby (because of averaging the fitness) The lower fitness parent should not mate because its fitness is not high enough to mate.

**Comment by Lumphie** [comment]
Update:

Still not sure if I want to compete for male trait. Feels counter intuitive to remove it since I need selection on the male trait as well.

**Comment by richelbilderbeek** [comment]
Also, OTOH, @rsetienne suggested to just use big populations: due to stochasticity you'll get a certain number of species that is more or less stable.

**Comment by Lumphie** [comment]
Can't test that now, GUI is giving errors :\

**Comment by richelbilderbeek** [comment]
I am (try to) working on it.

**Comment by Lumphie** [comment]
There is competition but no disruptive selection Argh!
:baby_chick: :hammer:

**Comment by richelbilderbeek** [comment]
I guess I've fixed the GUI, unassigning myself.
