### ISSUE TITLE
jaan (optional): modify .travis.yml

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#74]
In the Travis CI scripts, a lot is going on, that is easily copyable.

I hope you'll try to copy lines in `travis.yml` to work on the `jaan` files and projects.

Sure, I'll help you out if it does not work :sunglasses:

**Comment by JamesAndrews91** [comment]
Umm... So I did a little work on the jaan branch and it's giving this error:

The command "if [[ $TRAVIS_BRANCH == "jaan" ]]; then time ./jaan_EDSS; fi" exited with 139.
0.01s$ if [[ $TRAVIS_BRANCH == "jaan" ]]; then gprof jaan_EDSS > gprof.log; fi
gmon.out: No such file or directory
The command "if [[ $TRAVIS_BRANCH == "jaan" ]]; then gprof jaan_EDSS > gprof.log; fi" exited with 1.
0.00s$ if [[ $TRAVIS_BRANCH == "jaan" ]]; then head gprof.log -n 1000; fi

I don't know how to correct this.

**Comment by richelbilderbeek** [comment]
It probably meant that the executable `jaan_EDSS` crashed (with error 139). The following errors are consequences of that (one cannot profile a crashed executable).

I suggest to run `jaan_EDSS` on your computer locally to observe it crashing locally.

**Comment by richelbilderbeek** [comment]
According to [the Travis Build logs](https://travis-ci.org/richelbilderbeek/pbdmms/builds/181585742), it works.

I will close this Issue today, as there are too many open Issues now to my taste...
