### ISSUE TITLE
Hacking Tuesday/tomorrow 18:00-23:00 @sandervankasteel

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#77]
@LykeStuurman 
@Lumphie 
@JorikdeBoer 
@christophnetz 
@JamesAndrews91 

You are all invited to join hackerspace Hive5 @sandervankasteel tomorrow:
 * 18:00 door open
 * 18:30 order pizza
 * 23.00 must go home here

I know the address, it is close to the Poiesz (or whatever) south of the city center. Ask me verbally if you'd like to join somewhen evening.

**Comment by sandervankasteel** [comment]
Thanks for spreading the word @richelbilderbeek ! It's indeed near the Poiesz supermarket in the south of the city. If you need the address, you can also email me privately :)

**Comment by Lumphie** [comment]
Won't be able to make it. Work, commission work, and karaoke of idun!

**Comment by richelbilderbeek** [comment]
I'll be there!

**Comment by richelbilderbeek** [comment]
@christophnetz also was interested, I sent him your address and planning.

**Comment by christophnetz** [comment]
Hey, thanks for the invitation, I'm looking forward!

**Comment by richelbilderbeek** [comment]
It has been done :zzz:
