### ISSUE TITLE
Add Elles Jetten as a collaborator

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#82]
@JorikdeBoer is helping here get started. 

@JorikdeBoer: if she has a GitHub account, let me know, and I will add her as a collaborator.

**Comment by EllyJet** [comment]
Hey @richelbilderbeek Ik heb een account
- @EllyJet

**Comment by richelbilderbeek** [comment]
Excellent! You now have received an invitation email. Say yes and you're our newest collaborator. Welcome!

**Comment by richelbilderbeek** [comment]
Please close this Issue if you've confirmed you are a collaborator :+1:
