### ISSUE TITLE
Create new branch for @EllyJet

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pbdmms#83]
She can pick from any four-character name, e.g. `elly`, `elje`, `ejet`, `jetn`, `lsje`, etc.

@JorikdeBoer: I am not sure you know how to this. If you don't know, as @Lumphie :+1:

**Comment by JorikdeBoer** [comment]
@lumphie is unfortunately not here and I don't know how to do this, maybe you @richelbilderbeek could give some tips and tricks?

**Comment by richelbilderbeek** [comment]
I'll come down and show you two :coffee:

**Comment by richelbilderbeek** [comment]
Well done @richelbilderbeek!
