### ISSUE TITLE
Implement competition in BDM-model

### ISSUE THREAD

**Issue by JorikdeBoer** [richelbilderbeek/pbdmms#84]
First simple ideas for possible competition mechanism in BDM-model (and @richelbilderbeek ' s model?)

- Check at the start of reproduction the fitness of each individual parent to give the competition
  factor a certain impact on the population (to get disruptive selection), as in @Lumphie ' s ideas to   
  implement competition in his model.
- Each individual has it's own competition parameter/trait with a value between 0 and 10
  (depends on range of competition field).
- First generation individuals all have a random initial competition factor.
- Each generation there are one or more "best" maximum competition value(s)
- This maximum competition value (MCV) changes with 0.2 each generation
- An individual gets the competition parameter from one of it's parents, 
  (Otherwise the competition parameter would go faster towards an average?)

Examples: 
If an individual has a competition factor of 0.5 and the maximum competition value
is 0 and/or 1 the individuals chance to reproduce could decrease to 0.5
or if the individuals competition factor is not in a range of 0.5 of the MCV, 
the individuals chance to reproduce will decrease

How to implement competition:
1.Make for each individual a competition parameter/trait
(just like the fitness trait of 0 or 1 in the current model)
2.Create two maximum competition values and make sure each MCS value changes each generation
with steps of 0.2, so you have a changing/shifting competition optimum in your model
3.Before reproduction, check for each parent how far their competition parameter stands
from the MCS and implement the consequences on their chance to reproduce.

**Comment by richelbilderbeek** [comment]
Nice starting suggestion!

 * I think `competition parameter/trait` == `ecological trait` in the `kewe` model.
 * "Each individual has it's own competition parameter/trait with a value between 0 and 10": feels rather inelegant to me, I'd personally prefer a Gaussian-shaped resource distribution like `kewe` has
 * "First generation individuals all have a random initial competition factor": this feels to me as a lack of biology: one gets random values for a competition factor if there has been *no* selection on it
 * "This maximum competition value (MCV) changes with 0.2 each generation": it feels fun the have a moving optimal, but maybe a static optimum suffices

I recommend reading [1] as modifying your suggestion to be (1) simpler (2) closer to biology.

I look forward to the next suggestion :+1: 

## References

* Weissing, Franz J., Pim Edelaar, and G. Sander Van Doorn. "Adaptive speciation theory: a conceptual review." Behavioral ecology and sociobiology 65.3 (2011): 461-480.
