### ISSUE TITLE
Document clustering procedure

### ISSUE THREAD

**Issue by LykeStuurman** [richelbilderbeek/pbdmms#85]
@richelbilderbeek

**Comment by richelbilderbeek** [comment]
I assume I can find it in your code? I look forward to your words of wisdom :sunglasses:

**Comment by LykeStuurman** [comment]
Yes, but it is a piece of code to make a histogram: look at the function void histogram. But we did not perform a clustering procedure to find out if  individuals are also really reproductively isolated, as Sander did in his article.  @richelbilderbeek

**Comment by richelbilderbeek** [comment]
> as Sander did in his article
Could you give a reference? Is it van Doorn, Luttinkhuizen & Weissing 2001?

**Comment by LykeStuurman** [comment]
Yes

**Comment by LykeStuurman** [comment]
But anyway, we should get the same graph. As the ecological trait can only split if there is disruptive selection on the egg and sperm proteins--> and the ecological trait should then 'match' the protein sequence, otherwise it will be outcompeted. If that makes sense for you (bit of a crappy explanation)

**Comment by richelbilderbeek** [comment]
![hiero](https://cloud.githubusercontent.com/assets/2098230/20713129/5ffa35c6-b647-11e6-9ef1-56578aeb642f.png)

**Comment by richelbilderbeek** [comment]
If you know how it works, I volunteer to visualize it :angel:

**Comment by LykeStuurman** [comment]
yes, but we did not do that yet

**Comment by LykeStuurman** [comment]
and we probably are also not going to do that..

**Comment by richelbilderbeek** [comment]
> and we probably are also not going to do that..

Why not?

Need help to implement this function? If yes, feel free to use 'my minions', they'd benefit from helping you  :sunglasses:

**Comment by LykeStuurman** [comment]
I discussed this with Franjo and we think that looking at the ecological characters will be enough. At least for now.

**Comment by richelbilderbeek** [comment]
I've checked [1] and I'd be happy to be shown *where* the Magical Clustering Analysis is written down.

## References

 * Van Doorn, G. S., A. J. Noest, and P. Hogeweg. "Sympatric speciation and extinction driven by environment dependent sexual selection." Proceedings of the Royal Society of London B: Biological Sciences 265.1408 (1998): 1915-1919.

**Comment by LykeStuurman** [comment]
haha oke, I will take a look
