### ISSUE TITLE
Implement competition

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#90]
@JorikdeBoer
- [x]  give each individual a fitness value (gaussian curve) I can help.
- [x]  calculate competition, again I can help
- [ ]  test if you get disruptive selection (as expected)

@JorikdeBoer @lumphie
- [x]  If it works think about how to add it to jkr namespace

@richelbilderbeek 
- [x] When all of the above are checked adjust your model to work with jkr namespace

**Comment by Lumphie** [comment]
@JorikdeBoer How are you doing on this?

**Comment by richelbilderbeek** [comment]
Jorik does not need this. Richel neither. Some models give speciation already without competition :stuck_out_tongue:

**Comment by richelbilderbeek** [comment]
I think this Issue has become obsolete.
