### ISSUE TITLE
I get this error message from peregrine. I pushed and pulled it multiple times. What should I do? 

### ISSUE THREAD

**Issue by LykeStuurman** [richelbilderbeek/pbdmms#91]
@richelbilderbeek 
Your branch is behind 'origin/lyke' by 4 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
[s2203103@peregrine pbdmms]$ git pull
Updating d609cd3..27cf966
error: Your local changes to the following files would be overwritten by merge:
	parameters.txt
Please, commit your changes or stash them before you can merge.
Aborting
[s2203103@peregrine pbdmms]$

**Comment by Lumphie** [comment]
```
git add .
git commit -m "message"
git push

```?

**Comment by richelbilderbeek** [comment]
This is a consequence of #78 , I suggest `rm parameters.txt`

**Comment by LykeStuurman** [comment]
no.. it says I am up to date

**Comment by richelbilderbeek** [comment]
And, fixed? If yes, please close.

**Comment by richelbilderbeek** [comment]
@LykeStuurman And, fixed? If yes, please close.

**Comment by richelbilderbeek** [comment]
@LykeStuurman And, fixed? If yes, please close.
