### ISSUE TITLE
growingmicrotubuli.cpp is not evaluated by codecov

### ISSUE THREAD

**Issue by EllyJet** [richelbilderbeek/pbdmms#92]
I put the growingmicrotubuli cpp file online in elly.pro. But it does not show up on the codecoverage site. Could you explain why this is @richelbilderbeek ?

**Comment by richelbilderbeek** [comment]
I see [in the Travis build log](https://travis-ci.org/richelbilderbeek/pbdmms/builds/180084573#L1279) that it fails to compile, thus fails to run, thus has no code coverage, thus Codecov is right!

Fix the compile errors and you'll get your measurements :sunglasses:
