### ISSUE TITLE
Write bugreport runtime error: boost::algorithm::split

### ISSUE THREAD

**Issue by Lumphie** [richelbilderbeek/pbdmms#98]
`FIX_ISSUE_98`

**Comment by Lumphie** [comment]
Any updates on this one?

**Comment by richelbilderbeek** [comment]
Nope, but I will do.

**Comment by richelbilderbeek** [comment]
Created [my boost_algorithm_split_ubsan_warning respository](https://github.com/richelbilderbeek/boost_algorithm_split_ubsan_warning)

**Comment by richelbilderbeek** [comment]
Labeled this bug a [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug).
